### PR TITLE
JP: Miscellaneous additions

### PR DESCRIPTION
**Pull request by nickhall**
I tried to break it apart into a few different commits. As always feel free to disagree with any choices. Again based mostly on the RCT3 translation wiki.

### CODE REVIEW

**Comment by nickhall** [comment]
One possible point of discussion: use 研究する or 開発する? @jhako

**Comment by Gymnasiast** [comment]
@AaronVanGeffen

**Comment by jhako** [comment]
研究する is better. 開発する means I think we can use new rides at once.
Great works :)

**Comment by nickhall** [comment]
@Gymnasiast User @jhako is a native speaker and gave his endorsement of this PR so I'd say it's safe to merge.

**Pull request merged**
