### PR TITLE
add swahili language support

### PR DESCRIPTION
**Pull request by JacksiroKe**
I hope it pleases you add support for swahili language which is used in East Africa and parts of Africa

### CODE REVIEW

**Comment by marcinkunert** [comment]
Thanks for the input! There are still 3739 untranslated strings and the typical amount for any other language is around 300. Is this intended or are you still working on these?

**Comment by Gymnasiast** [comment]
Thanks for your PR.

For natural languages, starting off with a complete translation is not required. However, I would like the translation to have a few more translated sentences before I merge it.

I see you used the language code `sw-SW`, but there is no country with the code `SW`. Normally, you would put the code of your own country there. You can look up the code here: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Decoding_table

Once the pull request is merged, I will add the translation to the game.

**Comment by JacksiroKe** [comment]
@marcinkunert I was still laying the foundation of the major translation. Good thing I will use the check results as shown by the bot to see that I do everything as required.

Meanwhile @Gymnasiast kindly check here https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=sw where this information is outlined and to us in East Africa we know it that way as much as it is not in the Wikipedia page you just shared with me

**Comment by Gymnasiast** [comment]
@JacksiroKe The code consists of a language code (ISO 639-2) and a country code (ISO 3166-1 alpha-2), separated by a dash.

The ISO 639-2 language code for Swahili is indeed `sw`. 

But I'm not talking about the language code. I'm talking about the country code. There is no country code `SW`. 

Considering you're resident in Kenya, you're probably looking for `sw-KE` - Swahili as used in Kenya.

**Comment by tupaschoal** [comment]
Hey @JacksiroKe, did you face any issue we can help you?

**Pull request closed without merging**
