### PR TITLE
Update swedish + new strings 2016/03/14.txt

### PR DESCRIPTION
**Pull request by Nubbiy**
*Fixed spelling errors
*Filling in missed strings

*Added the new strings 
*Added myself as a maintainer in this document 
*Translated some new strings (50 %)
(*Not to be a douche - but corrected the spelling of "Maintainer" on the Note)

Overall progress: (75 %)

QUESTION: What is the difference between string 5649 & 5651?

### CODE REVIEW

**Comment by Nubbiy** [comment]
I'm really thankful for this mod and the work you guys are putting down so I want to help out too, sadly enough I don't know how to script but I would be more than happy to translate and maintain the Swedish language on OpenRTC2, it's not much but something.

**Comment by Gymnasiast** [comment]
Thank you for your contribution. :)

The difference between strings 5649 and 5651 is as follows:
5649 is about creating a new ride entity.
5651 is about constructing a ride, whether that is an old or a new ride.

You can get rid of the maintainer notes altogether, as the language is now maintained. The note is there because unmaintained language files are minimised, which means that untranslated strings are removed to make them fall back on English, making less likely to break when strings are changed.

**Comment by Nubbiy** [comment]
Thank you :)

Oh I see, will translate that immediately

I would, and I would be more than happy to continue translating this file, the problem is that I have no clue how as I don't use this site too often :(

**Comment by Gymnasiast** [comment]
If you look at the top if the PR you can see your edits are in your patch-2 branch. So you go to your own Localisation repository at https://github.com/Nubbiy/Localisation , then you click the branch dropdown and select patch-2. Then you navigate to the file you want to edit, and make your edits. As soon as you save that file, this PR will be updated.

**Comment by Gymnasiast** [comment]
I'm merging this now, as a stable is coming up. If you have any improvements the following days, we can still have them in stable btw.

**Comment by Nubbiy** [comment]
Thanks for telling me how to edit my branches, but have been a bit busy so couldn't modify the file, will try and translate more today

**Pull request merged**
