### PR TITLE
Update fr-FR.txt

### PR DESCRIPTION
**Pull request by siomy11**
If you are applying translations for an issue (or multiple), please list them below (if not, delete this text)

- Applying for issue: #1057

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Tagging @JoelTroch .

@siomy11 :
Are you a native (or near-native) speaker?

If not, we have a translator for French who is.

**Comment by JoelTroch** [comment]
The quality of this translation is good in overall but before it gets merged I would like to see the following changed:

"manège" is male, not female, so you would use "le" rather than "la".

"méchannique" is wrong, maybe you tried "mécanique" which means the domain but the person who repair mechanical stuff is "mécanicien" for a man or "mécanicienne" for a woman.

"à embauché" is almost correct, like this it means you "hired someone" (past action), it would be better to use "à embaucher" instead.

And final very minor remark, we frenchies have a weird convention of having a space before some type of punctuation, this applies to exclamation (!) and interrogation marks (?), so the final result would be "à embaucher !"

Otherwise, LGTM

**Comment by siomy11** [comment]
@JoelTroch @Gymnasiast seems like I need more practice! Will fix it right away 👍

**Comment by JoelTroch** [comment]
@Gymnasiast Now it's good for the merge ^^

**Pull request merged**
