### PR TITLE
de-DE: Update strings from 6586 to 6592

### PR DESCRIPTION
**Pull request by Gr33ndev**
Applying for issue(s):
- #2659
- #2658
- #2650 

My commit for the contributors file takes place in this PR: https://github.com/OpenRCT2/OpenRCT2/pull/20552

### CODE REVIEW

**Review by tupaschoal — COMMENTED** [review]
Thanks for volunteering to translate! From my perspective it looks good. Since @Wuzzy2 has been maintaining `de-DE` for a while, I'll give them a couple days to review

**Comment by Gr33ndev** [comment]
Sorry for your unnecessary work, I didn't know you were working also on it 😅

**Review by tupaschoal — APPROVED** [review]

**Comment by tupaschoal** [comment]
Thanks @Gr33ndev and @Wuzzy2 .

@Gr33ndev if you wish to become a regular `de-DE` maintainer, we have a system to have you notified and such, just let us know.

**Comment by Gr33ndev** [comment]
You‘re welcome!

Sure, let me know when there is something to translate to German :)

**Comment by tupaschoal** [comment]
Can you do a PR to add yourself? Should be pretty similar to this one https://github.com/OpenRCT2/Localisation/commit/3142e924d6b7dcc1d762dfce311bf6411f90d8fe

**Comment by Gr33ndev** [comment]
Sure: https://github.com/OpenRCT2/Localisation/pull/2669
Hope I did it right :)

**Pull request merged**
