### PR TITLE
[es-ES] Fixes of the es-ES.txt file.

### PR DESCRIPTION
**Pull request by frenchiveruti**
No issues related, I fixed many problems in the es-ES.txt file, such as typos and mistakes, also things that didn't make sense because the meaning was lost during translation.
Also a change on Readme.md so now new translators know about the commit guideline.

### CODE REVIEW

**Comment by frenchiveruti** [comment]
Please keep in mind that I have no idea how to split commits into different PR, so forgive me :)

**Comment by Gymnasiast** [comment]
I dropped the unrelated commit for you.

**Comment by Gymnasiast** [comment]
I merged a bit too quickly.

For the scenarios, you can translate the STR_SCNR and STR_PARK bits, as long as you leave the name between `<` and `>` intact.

**Comment by frenchiveruti** [comment]
Ok, thanks, should I push a PR with the readme file change I proposed?  
Can you show me how to not bundle all the commits into a single PR?  or link to me where should I look into it. Thanks

**Comment by Gymnasiast** [comment]
You have to use branches. Basically, you should keep your `master` branch the same as ours. If you want to make changes, you do:
```
git checkout master
git fetch upstream
git pull upstream master
git checkout -b name-of-your-new-branch
```
(This assumes you have your own repository as `origin` and ours as `upstream`.)

**Comment by frenchiveruti** [comment]
Aah I see, that was my mistake, I accidentally pushed a commit into the es-ES branch in my repo that modified the readme.
Thanks

**Pull request merged**
