### PR TITLE
CZE: (last) batch of strings translated

### PR DESCRIPTION
**Pull request by octaroot**
This should be the last batch of strings being translated to Czech. Right now, the only strings that are left untranslated are the names+descriptions of some of the rides/attractions - which are a real pain to translate/I'm not able to translate them accurately. Otherwise - after 3 days, everything else is now in Czech :-)

With 2k+ strings translated, it would be nice to be included in contributors file, it at all possible (don't know whether some special rules apply)

### CODE REVIEW

**Comment by Killermannvs** [comment]
In czech...

Ty jsi vsechny texty testoval ve hre?
Na prekladu taktez pracuju a ted se snazim nejak sloucit me a tve zmeny, asi pockam jeste na tento commit.

Pak chci zacit testovat primo ve hre.
Jinak vsechny texty nejsou prelozeny, je potreba doprelozit popisky ke scenarum...

**Comment by octaroot** [comment]
> Ty jsi vsechny texty testoval ve hre?
> Did you test all translated strings in-game?

Kontroloval jsem práci během překladu a taky jsem si zahrál jeden ze scénářů - vypadalo to OK. Mohl jsem ale něco přehlédnout - pokud ano, rád to opravím.
I was checking my results while translating. I also played a scenario with my translation, seemed fine to me. Of course I could have overlooked something - and if I did, I will fix it

> Na prekladu taktez pracuju a ted se snazim nejak sloucit me a tve zmeny, asi pockam jeste na tento commit.
> I'm also working on translating the strings, right now I'm attempting to merge mine and yours translations, but I guess I will wait for this pull request to get merged

OK, víc hlav víc ví. Kdyžtak si můžeš pro czech.txt sáhnout přímo ke mě do repa, ať nečekáš.
Cool, the more the merrier. You can fetch czech.txt from my repo, so that you don't just wait around.

> Jinak vsechny texty nejsou prelozeny, je potreba doprelozit popisky ke scenarum, coz je +- stejny mnozstvi textu jako ma samotna hra.
> Also don't forget that scenarios need translating too - and the amount of text is pretty much equal to the rest of the game.


Jasně, scénáře zatím nejsou - to jsou ale souvislé věty, není potřeba nad tím tolik přemýšlet - horší je s atrakcema. Taky myslím, že není tak důležitý příběh za scénářem, jako text hry samotné + cílů
Correct, scenario descriptions are not yet translated - but given that it's mostly long sentences, it's easier to translate - unlike rides/attractions. I think it's not as important as translating the game interface + goals.


Pokud tedy není jiný problém s tímto pull-requestem, tak asi nic nebrání merge.
If you haven't find any problems with this pull-request, then I guess it's merge-ready.

**Comment by Gymnasiast** [comment]
Is this ready for merging.


Also, you will be mentioned in the contributors file when I get around to it.

**Comment by octaroot** [comment]
Yes, the pull request is ready for merging.

Also, thank you! :-)

**Pull request merged**
