### PR TITLE
Improve es-ES translation

### PR DESCRIPTION
**Pull request by tupaschoal**
Applying for issue(s):
- #1773 
- #1781 
- #1786 
- #1789 
- #1804
- #1809 
- #1821
- #1826
- #1725
- #1675 

Also improving some translations and adding some from original fields.

(This is sourced from #1834 because I think it's great)

### CODE REVIEW

**Comment by frenchiveruti** [comment]
Thank you for your time, in the future if I do a translation of the files I'll just tag you and send you the file. I have zero idea on how to make git work.

**Comment by tupaschoal** [comment]
If you don't want to play around with git, the best way is to fork, do the changes in a small time window, submit the PR and then delete the fork once it is merged. That way you don't have to worry about rebasing or using the command line interface.

**Comment by frenchiveruti** [comment]
Yeah but doing that over and over gets really tiresome to be honest.  
I did that in the beginning but it got old so quickly...

**Comment by frenchiveruti** [comment]
It's just because I can't really sync the upstream git of OpenRCT2/Localisation with my fork, if I had some script to do it automatically every time I am about to translate, there would be no conflicts really.  
But I have 0 idea on how that's done.

**Comment by tupaschoal** [comment]
If you have git on the command line all you need to do is `git fetch upstream` then `git rebase upstream/master`.

Make sure you always submit a PR from a branch, and this is probably all the commands you'll need to use.

**Comment by Gymnasiast** [comment]
You can also just go here: https://github.com/OpenRCT2/Localisation/blob/master/data/language/es-ES.txt and click edit. No need to do difficult things with rebasing or anything.

**Comment by frenchiveruti** [comment]
Alright.
By the way the name of the PR should have es-ES at the beginning, right?
So the issues get the checkmarks on the es-ES checkbox.

**Comment by Gymnasiast** [comment]
The commits should have the form `es-ES: Apply #1234` (or `es-ES: Apply #1234, #1235` if it addresses multiple issues). For the PR, it doesn't matter too much. But it's probably easiest to use that form for both anyway.

I always have to manually check the checkboxes. But using the above form means that a reference gets posted on the issue, which makes it easier to keep track of.

**Comment by frenchiveruti** [comment]
Ah okay, I thought it was automagic

**Pull request merged**
