### PR TITLE
fix minor korean strings

### PR DESCRIPTION
**Pull request by skdltmxn**
This PR fixes a number of minor Korean strings

### CODE REVIEW

**Comment by tupaschoal** [comment]
@telk5093 do these changes seem fine to you?

**Comment by telk5093** [comment]
I think he translated "Fullscreen (borderless window)" literarily.
I translated it as meaning of "Fullscreen (window mode)" and it was my intend.
So, in my opinion, negetive.

Spacing words(``전체화면`` -> ``전체 화면``) are fine.

**Comment by skdltmxn** [comment]
I don't understand what "Fullscreen (window mode)" means since it literally is "Fullscreen" mode but with no borders. (We cannot resize the window unlike true Window mode)

Similarly PUBG also uses "테두리 없음" for borderless fullscreen mode.
image

**Comment by telk5093** [comment]
I understand what you're intend to say. But I translated the string as understanding as "window mode with fullscreen size" no matter it is resizable.
말씀하시고자 하는 바를 잘 알겠습니다만, 저는 해당 문구를 리사이징 가능한가와는 무관하게 "전체 화면 크기로 된 창 모드"로 이해하고 번역했습니다.

Note that _Diablo III_ uses ``창 모드(전체 화면)``. Please understand that the translation what I choose is similar like Diablo III's one.
디아블로 3가 비슷한 문구를 ``창 모드 (전체 화면)``으로 번역했고 제가 택한 번역은 디아블로 3의 것과 비슷한 것임을 알아주셨으면 합니다.
image

I think the best thing would be like ``테두리 없는 전체 화면 창``, but it is truncated since it's too long so I considered when I translated.
제 생각엔 가장 좋은 방법은 ``테두리 없는 전체 화면 창`` 정도일텐데, 문자열이 너무 길어서 잘리는 점도 번역할 때 고려했었습니다.

Nevertheless, if my opinion looks odd to you, please comment :)
그래도 제 의견이 이상해보이신다면 의견 부탁드립니다. :)

**Comment by skdltmxn** [comment]
Appreciate for your kind explanation :)

I agree that it is hard to find one best option of all. (How Diablo 3 was translated is pretty impressive!)
It seems like I should leave it as it is now. I will revert that part.

감사합니다.

**Comment by telk5093** [comment]
Merge this please.

**Pull request merged**
