### PR TITLE
Patch 8

### PR DESCRIPTION
**Pull request by danidoedel**
What do you think, shouldn't there be a colon after string 2700, 2738 and 2776? I think it would look more consistent.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Yes, I agree there should be one after string 2700, 2738 and 2776.

**Comment by danidoedel** [comment]
Ok, I'll add them here.

**Comment by danidoedel** [comment]
You can merge if all is fine.
Will you add the colons to UK?

**Comment by Gymnasiast** [comment]
Would you change (..) back to (Hoch), I don't think (..) is easy for non-tech savvy users.

**Comment by danidoedel** [comment]
Ok, saw that in the polish.txt and thought it would be a good idea. I'll change it back.

**Comment by Gymnasiast** [comment]
Thanks!
English UK is already pull requested: https://github.com/IntelOrca/OpenRCT2/pull/1173

**Pull request merged**
