### PR TITLE
FR: RCT2 + OpenRCT2 100% complete translation

### PR DESCRIPTION
**Pull request by rvgr**
Every string from RCT2 binaries ported over, plus slight corrections and improvements in translation. Will serve as a base for future discussion as to improve the translation.

I couldn't find some ride descriptions in the game, left them in English as they don't appear in game. However it seems that some are pulled from the ride data, some others from this file?

**To do**: OpenRCT2 strings. Scenario translations.

### CODE REVIEW

**Comment by rvgr** [comment]
Complete RCT2 + Open RCT2 translation.

**To do**: scenarios translations.

**Comment by rvgr** [comment]
100% complete translation. Looking for improvements.

**Comment by Gymnasiast** [comment]
I'll try to look at this tomorrow.

**Comment by Gymnasiast** [comment]
Why did you change many scenario names back to English, but changed others to French? (IMO, the original English names are preferable, but at least be consistent.)

**Comment by rvgr** [comment]
Well only some names were translated in French, I first reverted to English the already translated ones to be consistent.

Then I saw RCT2 scenario names were translated, so I translated all RCT1 scenario names for consistency.

Right now all scenario names are in French.

**Comment by Gymnasiast** [comment]
Ah, I see.

Thanks for your work!

**Pull request merged**
