### PR TITLE
ko-KR: Apply #806, #816

### PR DESCRIPTION
**Pull request by telk5093**

### CODE REVIEW

**Comment by Nubbie** [comment]
Looks good to me :+1:

**Comment by Nubbie** [comment]
Have reviewed the language and seen that it's missing a "{NEWLINE}", could you please insert it where the string breaks it? (Makes it easier to read in-game)
```
STR_5898    :{BLACK}Can't load the track, the file might be {NEWLINE} corrupted, broken or missing!
```

Also, seem like it's outside the box, I presume it's because it's too long, if too common, it maybe should be ignored 
test box

**Comment by Nubbie** [comment]
@telk5093 Does indeed break automatically but might break in a inconvenient spot that makes the sentence harder to read.

**Comment by telk5093** [comment]
@Nubbie Anyway I inserted it.

**Comment by Nubbie** [comment]
@telk5093 
If it feels better, you could remove the newline in the middle, just there for making it easier to follow and read the sentence

Breaks at the last work sadly enough, the text box covers a bit more of the text tho, to correct the problem fully, insert two {NEWLINE} in the end of the file 
A.k.a

```
STR_5898    :{BLACK}트랙을 불러올 수 없습니다.{NEWLINE}파일이 망가지거나 깨졌을 수 있습니다!{NEWLINE}{NEWLINE}
```

{NEWLINE}{NEWLINE} in the end results with
bfsdfdsgb

**Comment by telk5093** [comment]
@Nubbie There are many tooltips that is outside of the box in korean translations, but I cannot check all of them. I think inserting two {NEWLINE}s is not a complete solution to solve that issue.
Furthermore, there is no {NEWLINE}s in en-GB. It is ridiculous to add them in translations.
Anyway thanks to reporting and screenshots.

**Comment by Nubbie** [comment]
@telk5093 Know that it's outside the boxes in most tooltips thanks to the font and how it's programmed, more off a temporary solution until it gets solved :disappointed: 
The languages that doesn't use the original fonts have this problem

Ok from me :+1:

**Comment by telk5093** [comment]
Why this PR is not merged?

**Comment by Nubbie** [comment]
The person who often merges PR are on vacation :(

**Pull request merged**
