### PR TITLE
Fix the untranslated scenario names displayed in RCT1 scenario selection in Korean language.

### PR DESCRIPTION
**Pull request by qqkookie**
For RCT1 scenarios, the scenario names on the scenarios selection screen at the title screen, is  displayed in untranslated English language. , not in  the translated Korean name. See below screen capture.
So I exchanged the untranslated scenario names part and translated park name part in this PR to display translated scenario names in the screen. 
Also I improved Korean translations of the some few scenario names , especially the RCT1 expansion, "Added Attractions" name was "어트랙션 팩(Attraction Pack)" in Korea. Scenery names part was also added from "en-GB" language file.

BEFORE applying this PR:
korean

AFTER applying this PR:
korean2

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
@telk5093, your thoughts on this?

**Comment by telk5093** [comment]
Negative. I left them in english on purpose.

**Comment by telk5093** [comment]
Even if Added attraction pack is named "어트랙션 팩(Attraction Pack)" in korea, it is awkward that there is "팩(pack)" in attraction pack, and no in Loopy landscape(LL; 루피 랜드스케이프).
Since there is no more space to attach "팩(pack)" in LL to make them unity, so I did not attached "팩(pack)" in the attraction pack. And I think it is awkward to name it just "Attraction". That's why I translated it as "애디드 어트랙션(Added Attraction)"

@qqkookie RCT1 시나리오 이름은 일부러 영어로 놔둔 것입니다. (RCT1/2 구분 및 향수) 또한 한국에서 "어트랙션 팩"으로 정발되었다고 해도, 어트랙션 팩에만 '팩'이 붙고 루피 랜드스케이프에는 '팩'이 안 붙는 건 통일성이 안 맞습니다. 루피 랜드스케이프 탭에 '팩'을 붙일 공간이 없으므로 애디드 어트랙션에도 '팩'을 안 붙였고, '어트랙션'이라고만 이름짓는 것 또한 이상하기 때문에 '애디드 어트랙션'으로 번역했습니다.

**Comment by qqkookie** [comment]
Then, why leave the scenario names in English for RCT1 Only? For RCT2 and its expansions,  all the  scenario names are already displayed in translated Korean. IMHO there should be consistency between RCT1 and RCT2 . 

Please tell me a reason that Scenario names should not translated in Korean? Many other languages like Japanese or French language version translate the scenario names in Japanese or French langues respectively, even in RCT1 as well as RCT1. 
 Would you kindly explain us why Korean names for RCT1 should be only exception , for translation? BUt not RCT2 scenarios.

Below is screenshot of unmodified current version of for  RCT2  scenarios: Korean language 
default

And its expansion RCT2 Wacky World (Korean)


Below is Japanese and French version of RCT1 scenarios, all are translated in their languages. 




 I can not figure out reason Korean version does not do same as Japanese version translation case.

**Comment by qqkookie** [comment]
Why RCT1 should be in English for nostalgic reason and RCT2 is be in Korea? 
I have played the RCT1 in Korean language version back in the days. So to me, RCT1 in Korean is more nostalgic than RCT in English. Your nostalgic value in RCT1 in English is purely personal experience, which differs, person by person.  Most Korean people played RCT1 in Korean version, not English version.

So I think that for "nostalgic" reason of majority of Korean people who played RCT1 in Korean, it would be better to translate them all (both RCT1 and RCT2) in Korean name.

**Comment by Gymnasiast** [comment]
This is too controversial to merge. Closing it.

**Pull request closed without merging**
