### PR TITLE
Update portuguese_br.txt

### PR DESCRIPTION
**Pull request by renansimoes**
translation and revision of descriptions

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Please rebase this, I cannot commit it this way.

**Comment by renansimoes** [comment]
how do I do that?

**Comment by Gymnasiast** [comment]
It's probably easiest to go to [here](https://github.com/OpenRCT2/Localisation/blob/master/data/language/portuguese_br.txt), click the pencil icon and copy and paste your edits into there. But do make sure you have [these changes](https://github.com/OpenRCT2/Localisation/commit/dd9d7e92f32e70090e4c3b3896b7594a596c2b13) in your file first.

**Comment by renansimoes** [comment]
Yes, it has these changes

2015-12-01 18:33 GMT-02:00 Michael Steenbeek <notifications@github.com>:

**Comment by Gymnasiast** [comment]
Your language file is based on the file from 24 July, which has seen many changes in the meantime. Are you sure you have included every change in our repository in your file?

If so, follow the instructions in my previous message and you should be able to open another pull request that _can_ be merged.

**Comment by renansimoes** [comment]
Already done as you said: click the pencil icon and copy and paste mine
edits into there

2015-12-01 18:36 GMT-02:00 Renan Pereira Simões <renan.simoes.89@gmail.com>:

**Comment by Gymnasiast** [comment]
Then you need to create a pull request for that.

**Comment by renansimoes** [comment]
I've downloaded the file from repository that changed 10 days ago

2015-12-01 18:41 GMT-02:00 Michael Steenbeek <notifications@github.com>:

**Comment by Gymnasiast** [comment]
Sure, but open a PR for that new file you just saved please. I cannot merge this one.

**Pull request closed without merging**
