### PR TITLE
cs-CZ: slight improvements

### PR DESCRIPTION
**Pull request by Aroidzap**
Minor changes to some words.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
@octaroot 

Discussion can take place in Czech.

**Comment by octaroot** [comment]
Hi @Aroidzap, thanks for your new contribution ;-)

I reviewed your changes and they are all fine by me.

The only thing I'm not 100% sure about is reverting back to the untranslated term _looping_ (in favor of _lopink_). The dictionary I used listed both, so I opted for the more "Czech" translation. However since both are valid, feel free to leave it in - if you think it's more fitting.

**Comment by Aroidzap** [comment]
@octaroot I think that these taken over words are used more widely in untranslated forms.

**Comment by octaroot** [comment]
OK, ready to merge @Gymnasiast

**Pull request merged**
