### PR TITLE
pl-PL: Replace typewriter quotes

### PR DESCRIPTION
**Pull request by marcinkunert**
Applies #2121 for pl-PL

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Hi, I tried sending you a message on Discord. It's about the CI you added. Could you take a look?

**Comment by marcinkunert** [comment]
@Gymnasiast sure, I'll have a look

**Comment by Gymnasiast** [comment]
I see there are also some typewriter quotes in https://github.com/OpenRCT2/Localisation/blob/master/objects/pl-PL.json . Could you also tackle those in this PR?

**Comment by marcinkunert** [comment]
Done

**Pull request merged**
