### PR TITLE
Add ignore list to translation_check.py

### PR DESCRIPTION
**Pull request by tupaschoal**
Some strings are empty or are only composed of formatting stuff, so we shouldn't report them as being equal, which is a bit misleading and might make translators waste time checking stuff they don't really need to.

This adds an ignore list to those strings (mentioned in the list below for ease of checking). It will report if any of these strings that are not meant to have changed do, so that we can find out if there is something wrong or if it should be removed from the ignore list.

Note that because the CI runs the master version of the script, we won't actually see the result in this PR

```
STR_0000    :
STR_0001    :{STRINGID} {COMMA16}
STR_0824    :{BLACK}❌
STR_0839    :{UINT16} x {UINT16}
STR_0840    :{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{UINT16} x {UINT16}
STR_0865    :{STRINGID}
STR_0866    :{POP16}{STRINGID}
STR_0867    :{POP16}{POP16}{STRINGID}
STR_0868    :{POP16}{POP16}{POP16}{STRINGID}
STR_0869    :{POP16}{POP16}{POP16}{POP16}{STRINGID}
STR_0870    :{POP16}{POP16}{POP16}{POP16}{POP16}{STRINGID}
STR_0871    :{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{STRINGID}
STR_0872    :{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{STRINGID}
STR_0873    :{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{STRINGID}
STR_0874    :{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{STRINGID}
STR_0875    :{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{STRINGID}
STR_0876    :{BLACK}▼
STR_0954    :
STR_0956    :-180°
STR_0957    :-135°
STR_0958    :-90°
STR_0959    :-45°
STR_0960    :0°
STR_0961    :+45°
STR_0962    :+90°
STR_0963    :+135°
STR_0964    :+180°
STR_0965    :+225°
STR_0966    :+270°
STR_0967    :+315°
STR_0968    :+360°
STR_0969    :+405°
STR_0970    :+450°
STR_0971    :+495°
STR_0984    :{WINDOW_COLOUR_2}▲{BLACK}  {CURRENCY2DP}
STR_0985    :{WINDOW_COLOUR_2}▼{BLACK}  {CURRENCY2DP}
STR_0986    :{BLACK}{CURRENCY2DP}
STR_0989    :{STRINGID}
STR_1021    :{POP16}{POP16}{POP16}{POP16}{STRINGID}
STR_1134    :{POP16}{POP16}{POP16}{POP16}{POP16}{STRINGID} {COMMA16}
STR_1135    :{STRINGID} {COMMA16}
STR_1162    :{OUTLINE}{TOPAZ}{STRINGID}
STR_1165    :{STRINGID} - {STRINGID} {COMMA16}
STR_1170    :{STRING}
STR_1172    :{YELLOW}{STRINGID} 
STR_1191    :{BLACK}{STRINGID}
STR_1192    :{OUTLINE}{RED}{STRINGID}
STR_1193    :{WINDOW_COLOUR_2}{STRINGID}
STR_1218    :{BLACK}+
STR_1219    :{BLACK}-
STR_1331    :{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{VELOCITY}
STR_1332    :{VELOCITY}
STR_1333    :{STRINGID} - {STRINGID}{POP16}
STR_1334    :{STRINGID} - {STRINGID} {COMMA16}
STR_1342    :{DURATION}
STR_1343    :{DURATION} / 
STR_1345    :{LENGTH}
STR_1346    :{LENGTH} / 
STR_1384    :{YELLOW}{STRINGID}
STR_1388    :{OUTLINE}{GREEN}+ {CURRENCY}
STR_1389    :{OUTLINE}{RED}- {CURRENCY}
STR_1390    :{CURRENCY2DP}
STR_1391    :{RED}{CURRENCY2DP}
STR_1414    :{SMALLFONT}{BLACK}{DURATION}
STR_1419    :{SMALLFONT}{BLACK}{VELOCITY}
STR_1420    :{SMALLFONT}{BLACK}{LENGTH}
STR_1429    :{POP16}{POP16}{POP16}{CURRENCY2DP}
STR_1449    :{SPRITE} {STRINGID}{NEWLINE}({STRINGID})
STR_1450    :{INLINE_SPRITE}{09}{20}{00}{00}{SPRITE} {STRINGID}{NEWLINE}({STRINGID})
STR_1451    :{STRINGID}{NEWLINE}({STRINGID})
STR_1528    :
STR_1529    :
STR_1530    :
STR_1532    :
STR_1541    :
STR_1544    :
STR_1545    :
STR_1546    :
STR_1547    :
STR_1548    :
STR_1549    :
STR_1562    :
STR_1563    :
STR_1564    :
STR_1566    :
STR_1575    :
STR_1578    :
STR_1579    :
STR_1580    :
STR_1581    :
STR_1582    :
STR_1583    :
STR_1601    :
STR_1602    :
STR_1603    :
STR_1605    :
STR_1606    :
STR_1607    :
STR_1608    :
STR_1609    :
STR_1610    :
STR_1611    :
STR_1612    :
STR_1613    :
STR_1614    :
STR_1615    :
STR_1633    :
STR_1634    :
STR_1635    :
STR_1637    :
STR_1638    :
STR_1639    :
STR_1640    :
STR_1641    :
STR_1642    :
STR_1643    :
STR_1644    :
STR_1645    :
STR_1646    :
STR_1647    :
STR_1675    :{POP16}{VELOCITY}
STR_1690    :{WINDOW_COLOUR_2}{STRINGID}{NEWLINE}{BLACK}{STRINGID}
STR_1731    :{WHITE}{STRINGID} - - 
STR_1744    :{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{COMMA16}
STR_1749    :{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{DURATION}
STR_1771    :{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{COMMA16}
STR_1778    :{STRINGID} - - 
STR_1799    :{POP16}{POP16}{POP16}{POP16}{POP16}{CURRENCY2DP}
STR_1812    :{SMALLFONT}{BLACK}{STRINGID}
STR_1817    :({COMMA32})
STR_1845    :{MONTHYEAR}
STR_1867    :{BLACK}{COMMA16} {STRINGID}
STR_1871    :{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{COMMA16}
STR_1875    :{BLACK} {SPRITE}{BLACK} {STRINGID}
STR_1912    :{MONTH}
STR_1913    :{BLACK}+{CURRENCY2DP}
STR_1914    :{BLACK}{CURRENCY2DP}
STR_1915    :{RED}{CURRENCY2DP}
STR_1917    :{POP16}{POP16}{POP16}{CURRENCY}
STR_1926    :{SMALLFONT}
STR_1957    :{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{COMMA16}
STR_1958    :{COMMA16}
STR_1970    :{WINDOW_COLOUR_2}
STR_1971    :{WINDOW_COLOUR_2}
STR_1972    :{WINDOW_COLOUR_2}
STR_1974    :{WINDOW_COLOUR_2}
STR_1983    :{WINDOW_COLOUR_2}
STR_1986    :{WINDOW_COLOUR_2}
STR_1987    :{WINDOW_COLOUR_2}
STR_2117    :{WINDOW_COLOUR_2}
STR_2118    :{WINDOW_COLOUR_2}
STR_2119    :{WINDOW_COLOUR_2}
STR_2121    :{WINDOW_COLOUR_2}
STR_2215    :{STRINGID}{NEWLINE}({STRINGID})
STR_2216    :{WINDOW_COLOUR_2}{COMMA16}°C
STR_2217    :{WINDOW_COLOUR_2}{COMMA16}°F
STR_2222    :{SMALLFONT}{BLACK}{STRINGID}
STR_2235    :{SMALLFONT}{STRINGID} {STRINGID}
STR_2289    :{STRINGID} {STRINGID}
STR_2454    :{SMALLFONT}{BLACK}{CURRENCY2DP} -
STR_2763    :???
STR_2781    :{STRINGID}:
STR_2996    :{BLACK}ABC
STR_2997    :{GREY}ABC
STR_2998    :{WHITE}ABC
STR_2999    :{RED}ABC
STR_3000    :{GREEN}ABC
STR_3001    :{YELLOW}ABC
STR_3002    :{TOPAZ}ABC
STR_3003    :{CELADON}ABC
STR_3004    :{BABYBLUE}ABC
STR_3005    :{PALELAVENDER}ABC
STR_3006    :{PALEGOLD}ABC
STR_3007    :{LIGHTPINK}ABC
STR_3008    :{PEARLAQUA}ABC
STR_3009    :{PALESILVER}ABC
STR_3020    :
STR_3096    :{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{VELOCITY}
STR_3212    :{POP16}{COMMA16} x {PUSH16}{COMMA16}
STR_3246    :{WINDOW_COLOUR_2}{CURRENCY}
STR_3302    :{WINDOW_COLOUR_2}{MONTHYEAR}
STR_3309    :{WINDOW_COLOUR_2}{COMMA16}
STR_3310    :{WINDOW_COLOUR_2}{LENGTH}
STR_3311    :{WINDOW_COLOUR_2}{COMMA2DP32}
STR_5138    :{SMALLFONT}{WINDOW_COLOUR_2}{STRINGID}
STR_5139    :{WHITE}{STRINGID}
STR_5151    :,
STR_5152    :.
STR_5182    :{INT32}
STR_5298    :{RED}{STRINGID}
STR_5299    :{LIGHTPINK}{STRINGID}
STR_5375    :▲
STR_5376    :▼
STR_5462    :{CURRENCY}
STR_5467    :ALT + 
STR_5485    :{SMALLFONT}{STRING}
STR_5486    :{BLACK}{COMMA16}
STR_5633    :CMD + 
STR_5918    :{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{POP16}{COMMA16}
STR_5919    :{COMMA16}
STR_6012    :{COMMA1DP16}
STR_6034    :{SMALLFONT}{BLACK}{STRING}
STR_6059    :»
STR_6062    :{OUTLINE}{GREEN}+ {CURRENCY2DP}
STR_6063    :{OUTLINE}{RED}- {CURRENCY2DP}
STR_6164    :{WHITE}❌
STR_6187    :{MEDIUMFONT}{OUTLINE}{WINDOW_COLOUR_2}{STRING}
STR_6201    :{MONTH}
STR_6229    :{WINDOW_COLOUR_2}{STRINGID}: {STRINGID}
STR_6230    :{STRINGID}:
STR_6231    :{WINDOW_COLOUR_2}{STRINGID}: {MOVE_X}{185}{STRINGID}
STR_6329    :{STRING}{STRINGID}
STR_6360    :{SMALLFONT}{BLACK}{COMMA32}
```

**EDIT1**: Removed STR_5813, STR_5814, STR_6308 from ignore list per Michael's request.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Please remove all strings containing quotation marks (“ and ”). These differ from language to language and should not be ignored.

**Comment by tupaschoal** [comment]
There were just three of those, which I just removed:
```
STR_5813    :“{STRING}”
STR_5814    :{WINDOW_COLOUR_1}“{STRING}”
STR_6308    :“{STRINGID}{OUTLINE}{TOPAZ}”{NEWLINE}{STRINGID}
```

**Review by Gymnasiast — APPROVED** [review]
LGTM.

Would like an ack from @marcinkunert .

**Comment by marcinkunert** [comment]
Looks good to me too

**Pull request merged**
