### PR TITLE
Fix translation check action 

### PR DESCRIPTION
**Pull request by marcinkunert**
Changed translation check action trigger in order to work around a lack of write access when executed on fork. Hopefully this does the trick.

### CODE REVIEW

**Review by Gymnasiast — APPROVED** [review]

**Comment by marcinkunert** [comment]
> Check has not run at all

I'm guessing that's because this particular PR touches the workflow which should be triggered. Either way if the previous trigger is broken than this PR has a chance to fix it.

**Comment by tupaschoal** [comment]
Maybe touch some language files in a separate commit so we can test it on the pr, then we drop that commit later before merging

**Comment by marcinkunert** [comment]
ASASIK GitHub will trigger the workflow which is on the master branch. There is a working example on my fork: https://github.com/marcinkunert/OpenRCT2_Localisation/pull/7 
Come on guys it's broken anyways atm, why not simply approve the pr and check what will happen?

**Comment by tupaschoal** [comment]
I understand it can be frustrating to have the check broken. We just want to get it right with fewer back and forth steps, in case it's not the final solution.

**Comment by marcinkunert** [comment]
If you want to help out then creating a PR to this repo: https://github.com/marcinkunert/OpenRCT2_Localisation should be a good way of testing if this actually works.

**Comment by tupaschoal** [comment]
I've read a bit about the `pull_request_target` and I think the change makes sense. As far as I'm concerned, it doesn't run in this pr because it's a protection mechanism from GitHub

**Review by tupaschoal — APPROVED** [review]

**Pull request merged**
