### PR TITLE
New strings, many improvements

### PR DESCRIPTION
**Pull request by danidoedel**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
STR_0010 should become 'Boat hire'. (IntelOrca said 'boat ride', but that's not really accurate. (Examples of boat hire are Swans, Water tricycles, bumper boats, or simply the boat hire from RCT1.)

**Comment by danidoedel** [comment]
Fixed ;)

**Comment by IntelOrca** [comment]
I said in #81 that you would need to change the name for several rides in English (US).

**Comment by danidoedel** [comment]
Oh ok sorry, didn't see that. I'll try to fix it.

**Comment by danidoedel** [comment]
I hope it's ok now...

**Comment by Gymnasiast** [comment]
I think it's ok. :)

**Pull request merged**
