### PR TITLE
pl-PL: Apply #1979

### PR DESCRIPTION
**Pull request by marcinkunert**
Applying for issue: #1979

Hopefully translation check works as intended now.

### CODE REVIEW

**Comment by marcinkunert** [comment]
Yay it worked 🎉

Two quirks:

- One failed test - GitHub probably saved the result from previous check on that commit. 
- Changes on languages other than `pl-PL` - my branch wasn't rebased completely. Not sure what I can do to avoid this though other than keeping the repo rebased

**Comment by marcinkunert** [comment]
Looks a lot better after rebasing

**Comment by Gymnasiast** [comment]
Most translators are not very good with Git. We cannot expect them to rebase. The results really have to be correct even if the branch is not rebased.

**Comment by marcinkunert** [comment]
I agree. Opened an issue for that #1991

**Pull request merged**
