### PR TITLE
de-DE: Use German quotation style

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by danidoedel** [comment]
I wouldn't mix double quotes and single quotes. Just use double quotes for everything ;)
Also, you missed some strings like https://github.com/OpenRCT2/Localisation/pull/1524/files#diff-3841c99f5b7b3b48a6e056eacbe1fd97R2692

**Comment by Gymnasiast** [comment]
Isn't the idea in German that you use double quotes for actual quotations (and thoughts) and single quotes for other things?

**Comment by danidoedel** [comment]
No not really. I have never really used single quotes for anything, but you would use them in another quotation which is already using double quotes.

**Comment by ccoors** [comment]
Why not „“ on STR_1080, STR_1081, STR_1085, STR_1086, STR_1087? I think this is wrong.

**Comment by danidoedel** [comment]
Because it‘s easy to overlook them if 4 different styles were used. Of course they should be changed as well.

**Pull request merged**
