### PR TITLE
pl-PL apply #1979

### PR DESCRIPTION
**Pull request by marcinkunert**
Applying for issue #1979
I'll keep it as a draft in order to test the translation check action

### CODE REVIEW

**Comment by tupaschoal** [comment]
(seems like something is wrong in the script)

**Comment by marcinkunert** [comment]
The script is fine, but there seems to be a limitation to the commit action so that it only works if the PR author has edit rights for the repo (https://github.com/actions/first-interaction/issues/10). I'm currently looking for a fix for that.

**Comment by tupaschoal** [comment]
I think you need to use the GH actions secret

**Comment by marcinkunert** [comment]
That seems to be the case. I'll test that out on my fork. Afterwards I would like to ask you to create a token with write rights to this repo and setup it as a secret.

**Comment by tupaschoal** [comment]
I guess you can use the default built-in token every repo has, `secrets.GITHUB_TOKEN`

**Comment by marcinkunert** [comment]
This one gets used by default but lacks write access to PR's which is apparently needed.

**Comment by tupaschoal** [comment]
I think it'd work because the PR runs on upstream not the fork. I guess that column is if you were trying to run it in a pr in your own repo (?), Not sure though

**Comment by marcinkunert** [comment]
Hopefully fixed in #1989

**Comment by marcinkunert** [comment]
Closing this PR. I'll create a new one in order to check if the translation check does work now as intended.

**Pull request closed without merging**
