### PR TITLE
Update russian.txt

### PR DESCRIPTION
**Pull request by Soosisya**
more translating stuff

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Thanks. :)
A question: which TTF font works well with Russian? Does Arial work, for example? We need to choose a TTF font in OpenRCT2 to display Cyrillic script.

**Comment by Soosisya** [comment]
yes, it does, Times new roman works as well
By the way, i've downladed the lastest build and still find that russian language isn't listed in the option menu yet

**Comment by Gymnasiast** [comment]
That's right, but I explained above why that was. We will add support for it soon.

**Comment by IntelOrca** [comment]
It would better to use a sans-serif font rather than a serif font if possible.

**Comment by Gymnasiast** [comment]
Well, Arial, then.

**Comment by IntelOrca** [comment]
Yes, we will need be able specify multiple fonts anyway as not all languages are going to have a single font that everyone has. We will also need to allow user override.

**Comment by tsunamistate** [comment]
Arial would be nice, but I also think, Open Sans or Roboto would also be good alternatives, and they're included in most popular Linux distributions.
If you guys would tell how to temporarily include Russian support w/ a font I could experiment and pick a font that looks good.

**Comment by IntelOrca** [comment]
They are defined in language.cpp, you will need to be able to compile the project.

**Comment by tsunamistate** [comment]
Let's continue this conversation on Localisation gitter

**Pull request merged**
