### PR TITLE
Remove duplicate translations

### PR DESCRIPTION
**Pull request by tupaschoal**
Found with #2617 

Can you check your languages whether I removed the right ones @J0anJosep, @LucaRed, @Goddesen, @daihakken ?

Changes double check:
- [x] ca-ES
- [x] en-US
- [x] hu-HU
- [ ] it-IT
- [ ] nb-NO
- [x] zh-TW

### CODE REVIEW

**Comment by Gymnasiast** [comment]
en-US looks fine too. (I mostly maintained it, so I figured I’d check.)

**Comment by J0anJosep** [comment]
ca-ES changes are fine too.

**Comment by daihakken** [comment]
Thanks for finding out the duplicate strings, and the changes look good to me.

On 12 Apr 2023, at 02:03, Tulio Leao ***@***.******@***.***>> wrote:


Found with #2617<https://github.com/OpenRCT2/Localisation/pull/2617>

Can you check your languages whether I removed the right ones @J0anJosep<https://github.com/J0anJosep>, @LucaRed<https://github.com/LucaRed>, @Goddesen<https://github.com/Goddesen>, @daihakken<https://github.com/daihakken> ?

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/OpenRCT2/Localisation/pull/2618

Commit Summary

  *   1cd1c81<https://github.com/OpenRCT2/Localisation/pull/2618/commits/1cd1c810c4885849b12d0634eaefee681c05a0a9> ca-ES: Remove duplicate translations
  *   f0e1705<https://github.com/OpenRCT2/Localisation/pull/2618/commits/f0e170519145fc69c18ee9b53a9a59cf9454b3d0> en-US: Remove duplicate translations
  *   6d0d0e8<https://github.com/OpenRCT2/Localisation/pull/2618/commits/6d0d0e856c7504c4a9d76e5d53eb2ba09b30a0ed> hu-HU: Remove duplicate translations
  *   4b1642b<https://github.com/OpenRCT2/Localisation/pull/2618/commits/4b1642bee7738b001828abff5eaa7c688280c3af> it-IT: Remove duplicate translations
  *   192355e<https://github.com/OpenRCT2/Localisation/pull/2618/commits/192355eae9a0dc8387d52619def868e74190824f> nb-NO: Remove duplicate translations
  *   3a4987b<https://github.com/OpenRCT2/Localisation/pull/2618/commits/3a4987bb05cbdc6c3d72a5d1e5f78467ec42cb00> zh-TW: Remove duplicate translations

File Changes

(6 files<https://github.com/OpenRCT2/Localisation/pull/2618/files>)

  *   M data/language/ca-ES.txt<https://github.com/OpenRCT2/Localisation/pull/2618/files#diff-ef6ec2dc5518eb4d3b201aa72baa8173ca4831fbcdc21b8d6019214db44ca72e> (12)
  *   M data/language/en-US.txt<https://github.com/OpenRCT2/Localisation/pull/2618/files#diff-7c79db42143912dac8a53a97cd7db9dce736e2a7efcbcbabdb0b643e97b086cf> (2)
  *   M data/language/hu-HU.txt<https://github.com/OpenRCT2/Localisation/pull/2618/files#diff-ca792749a2fca15012d2d6cd3f705e44912ea8b8b3a0d8568581c09fc95affae> (8)
  *   M data/language/it-IT.txt<https://github.com/OpenRCT2/Localisation/pull/2618/files#diff-d0594debc2807aa00a5739dcbcf7ecdee03e2cb0472730bca1a67386228120e1> (1)
  *   M data/language/nb-NO.txt<https://github.com/OpenRCT2/Localisation/pull/2618/files#diff-3e0b752c2773fffd7365295c00e2d156cda19773ac4f34721c054d1541630967> (7)
  *   M data/language/zh-TW.txt<https://github.com/OpenRCT2/Localisation/pull/2618/files#diff-8009996f76ade88760ca70a7fd02b1471991b6998b896346adacbe2431a700f6> (3)

Patch Links:

  *   https://github.com/OpenRCT2/Localisation/pull/2618.patch
  *   https://github.com/OpenRCT2/Localisation/pull/2618.diff

**Comment by tupaschoal** [comment]
I'll merge this as is, since most of the affected languages were verified already. @LucaRed and @Goddesen if you have anything to  say afterwards, just let me know and I can change it.

**Pull request merged**
