### PR TITLE
Update french.txt

### PR DESCRIPTION
**Pull request by ghost**
Translate, update, corrections, and remove manufacturer name (Intamin ...)

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Please restore the Intamin string. It's part of an Easter Egg. If you feel it should be removed, please discuss it on the Gitter for OpenRCT2.

**Comment by GuillaumeCardon** [comment]
I think it's an open door to fights, dick contests,  between fanboys... Intamin, Vekoma, Mack... 
We keep "Intamin" for satisfaction notification ? Ok, but we can write "Vekoma" when ride is boring... :p
To me, notifications must be neutral, if not, it's an endless debate..
But if you want to keep this "easter egg", ok, no prob for me.

**Comment by Gymnasiast** [comment]
It's not a message that is triggered on satisfaction, it's an Easter Egg that was in RCT2, and only triggered when a guest has a certain name (of one of RCT2's developers). Apparently you are not aware of that, and yet you have an opinion about it.

**Comment by GuillaumeCardon** [comment]
Thanks for your answer, it's cool :)
Interest to open a debate of this ? Delete the branch, and all is allright :)

**Comment by Gymnasiast** [comment]
If you think this feature upsets the neutrality of the game, you can discuss it in an issue here: https://github.com/OpenRCT2/OpenRCT2/issues . Do note you need to give a guest a specific name in order to trigger it, it's not a message the average user would encounter by accident.

You can revert the two edited strings by going to your `patch-1` branch and editing the `french.txt` file again if you want to have the other strings merged.

**Comment by GuillaumeCardon** [comment]
No, no interest to discuss, i see an example on this thread ;)
I know these type of easter egg on RCT1 (Chris Swayer, John Wardley, etc.), but you're right, i made a mistake.
Keep Intamin and whatever you want on the patch-1 branch.

**Comment by Gymnasiast** [comment]
Superseded by newer PRs.

**Pull request closed without merging**
