### PR TITLE
cs-cz apply #1942

### PR DESCRIPTION
**Pull request by octaroot**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Hi, could you use the format `cs-CZ: Apply #1942` next time? (It would save me a bit of time.)

**Comment by Gymnasiast** [comment]
@Oh, another thing. The issue in question has been updated because the last string was wrong. Could you do an update?

**Comment by Gymnasiast** [comment]
@octaroot Oh another thing. The issue in question has been updated because the last string was wrong. Could you do an update?

**Comment by octaroot** [comment]
No update needed, my translation is broad enough to express the updated string

**Pull request merged**
