### PR TITLE
fix #625 for italian

### LINKED ISSUE #625: STR_5815 -> STR_5859
Added tool-tips strings from [#3394](https://github.com/OpenRCT2/OpenRCT2/pull/3394) _and with correction of [#3534](https://github.com/OpenRCT2/OpenRCT2/pull/3534)_

**New added strings:**

```
#tooltips
STR_5815    :{SMALLFONT}{BLACK}Display FPS counter in-game
STR_5816    :{SMALLFONT}{BLACK}Sets ratio to scale the game by.{NEWLINE}Most useful when playing in{NEWLINE}high resolutions
STR_5817    :{SMALLFONT}{BLACK}[Requires hardware display]{NEWLINE}Sets UI scaling type
STR_5818    :{SMALLFONT}{BLACK}[Requires hardware display]{NEWLINE}Use nearest neighbour scaling{NEWLINE}when window scaling factor set{NEWLINE}to integer values (1, 2, 3, etc)
STR_5819    :{SMALLFONT}{BLACK}[Requires hardware display]{NEWLINE}Pause the game if Steam{NEWLINE}in-game overlay is opened
STR_5820    :{SMALLFONT}{BLACK}Minimise the game if focus is{NEWLINE}lost while in fullscreen mode
STR_5821    :{SMALLFONT}{BLACK}Changes the colour of the construction marker when building rides,{NEWLINE}paths, shops, scenery, etc.
STR_5822    :{SMALLFONT}{BLACK}Cycle between day and night.{NEWLINE}Full cycle takes one in-game month
STR_5823    :{SMALLFONT}{BLACK}Display banners in uppercase (RCT1 behaviour)
STR_5824    :{SMALLFONT}{BLACK}Disables lightning effect{NEWLINE}during a thunderstorm
STR_5825    :{SMALLFONT}{BLACK}Keep the mouse cursor in the window
STR_5826    :{SMALLFONT}{BLACK}Invert right mouse dragging of the viewport
STR_5827    :{SMALLFONT}{BLACK}Sets the color scheme used for the GUI
STR_5828    :{SMALLFONT}{BLACK}Changes what measurement format is used for distances, speed, etc.
STR_5829    :{SMALLFONT}{BLACK}Changes what currency format is used. Purely visual, there is no exact exchange rate implementation
STR_5830    :{SMALLFONT}{BLACK}Changes what language is used
STR_5831    :{SMALLFONT}{BLACK}Changes what format the{NEWLINE}temperature is displayed in
STR_5832    :{SMALLFONT}{BLACK}Show height as generic units instead of measurement format set under "Distance and Speed"
STR_5833    :{SMALLFONT}{BLACK}Changes what date format is used
STR_5834    :{SMALLFONT}{BLACK}Select which audio device OpenRCT2 will use
STR_5835    :{SMALLFONT}{BLACK}Mute the game if the window loses focus
STR_5836    :{SMALLFONT}{BLACK}Select music to use on the main menu.{NEWLINE}Selecting RCT1 theme requires that you copy 'data/css17.dat' from your RCT1 game folder to 'data/css50.dat' in your RCT2 folder.
STR_5837    :{SMALLFONT}{BLACK}Create and manage custom UI themes
STR_5838    :{SMALLFONT}{BLACK}Show a separate button for the finance window in the toolbar
STR_5839    :{SMALLFONT}{BLACK}Show a separate button for the research and development window in the toolbar
STR_5840    :{SMALLFONT}{BLACK}Show a separate button for the cheats window in the toolbar
STR_5841    :{SMALLFONT}{BLACK}Show a separate button for the recent news window in the toolbar
STR_5842    :{SMALLFONT}{BLACK}Sort scenarios into tabs by their difficulty (RCT2 behaviour) or their source game (RCT1 behaviour)
STR_5843    :{SMALLFONT}{BLACK}Enable scenario unlocking (RCT1 behaviour)
STR_5844    :{SMALLFONT}{BLACK}Stay connected to a multiplayer server{NEWLINE}even if a desync or error occurs
STR_5845    :{SMALLFONT}{BLACK}Adds a button for{NEWLINE}debugging tools to the toolbar.{NEWLINE}Enables keyboard shortcut for developer console
STR_5846    :{SMALLFONT}{BLACK}Set often OpenRCT2 automatically saves
STR_5847    :{SMALLFONT}{BLACK}Select park sequence used on the title screen.{NEWLINE}Title sequences from RCT1/2 require imported scenarios to function
STR_5848    :{SMALLFONT}{BLACK}Create and manage custom title sequences
STR_5849    :{SMALLFONT}{BLACK}Automatically place{NEWLINE}newly hired staff members
STR_5850    :{SMALLFONT}{BLACK}Newly hired handymen mow{NEWLINE}grass by default (RCT1 behaviour)
STR_5851    :{SMALLFONT}{BLACK}Sets the default inspection interval{NEWLINE}on newly built rides
STR_5852    :{SMALLFONT}{BLACK}Set the name of the TwitchTV channel that will be used for Twitch integration
STR_5853    :{SMALLFONT}{BLACK}Toggle sound effects on/off
STR_5854    :{SMALLFONT}{BLACK}Toggle ride music on/off
STR_5855    :{SMALLFONT}{BLACK}Set regular fullscreen, borderless fullscreen{NEWLINE}or windowed display
STR_5856    :{SMALLFONT}{BLACK}Set game resolution when in fullscreen mode
STR_5857    :{SMALLFONT}{BLACK}Game options
STR_5858    :{SMALLFONT}{BLACK}Use GPU for displaying instead of CPU. Improves compatibility with screen capture software. May slightly decrease performance.
STR_5859    :{SMALLFONT}{BLACK}Enables frame tweening for visually{NEWLINE}smoother gameplay. When disabled,{NEWLINE}the game will run at 40 FPS.
```

### PR DESCRIPTION
**Pull request by Mte90**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
I can't merge it like this due to merge conflicts. 
Please go [here](https://github.com/OpenRCT2/Localisation/blob/master/data/language/it-IT.txt), click the pencil and copy your changes. Then follow the on-screen instructions to create a PR.

**Comment by Nubbie** [comment]
While you're at it, could you also change and translate STR_3160 to:
```
STR_3160        :{SMALLFONT}{BLACK}Select the number of circuits per ride
```

**Comment by Mte90** [comment]
PR update and forced from the latest translations, I used the wrong branch to translate.
I've added also the #645

**Comment by Nubbie** [comment]
Still seems to have some conflicts, did you do as Gymnasiast said? :v 

Also, dont like to be that guy buuuut
you could also at least take a look at #632 and see if there is anything that could be changed to make it sound better in Italy :p

**Comment by Mte90** [comment]
I open a new pr to avoid that problems.

**Pull request closed without merging**
