### PR TITLE
Created japanese file with some basic translations

### PR DESCRIPTION
**Pull request by nickhall**
Chinese and Korean translations are up, but no Japanese! We can fix this.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Thanks for your contribution!
Could you suggest a Japanese font to use that is likely to be installed on most Windows computers?

**Comment by nickhall** [comment]
Meiryo or MS Gothic might be good choices!

**Comment by AaronVanGeffen** [comment]
MS Gothic is the most compatible choice, I think -- it's available from XP onwards. Meiryo has been available since Vista, but is mostly for use with anti-aliasing / cleartyping, I think -- which OpenRCT2 currently does not support.

**Comment by IntelOrca** [comment]
It would be nice to use DirectWrite in the future so we can properly do ClearType text.

**Pull request merged**
