### PR TITLE
Rework for Readme - Live language status 

### PR DESCRIPTION
**Pull request by Nubbie**
Now when we[ can log changes to the languages,](https://github.com/OpenRCT2/Localisation/commit/f5d1f08b72d235d2b8eb31f404afb1f1e0d2e74c) this layout and re-work could be brought up for suggestions, thoughts and discussions :smile: 

Changing the layout and the file mostly for getting more information easier out to the people when;

**Pros:**
*Better language status
*Public maintainers name for contact
*Good for new translators
*Information on how to maintain a language

Inspired by https://translation.steampowered.com/

### CODE REVIEW

**Comment by Nubbie** [comment]
eshsehseh

**Comment by Wirlie** [comment]
I have one question, What will happen with the deprecated strings?
I removed these strings from my language....

Current info:

> ```
  warning: No string for STR_0838:    <removed string - do not use>
  warning: No string for STR_0841:    <removed string - do not use>
  warning: No string for STR_0842:    <removed string - do not use>
  warning: No string for STR_0843:    <removed string - do not use>
  warning: No string for STR_0844:    <removed string - do not use>
  warning: No string for STR_0845:    <removed string - do not use>
  warning: No string for STR_0846:    <removed string - do not use>
  warning: No string for STR_0890:    <removed string - do not use>
  warning: No string for STR_1651:    <removed string - do not use>
  warning: No string for STR_1652:    <removed string - do not use>
  warning: No string for STR_1892:    <removed string - do not use>
  warning: No string for STR_1893:    <removed string - do not use>
  warning: No string for STR_2317:    <removed string - do not use>
  warning: No string for STR_2318:    <removed string - do not use>
  warning: No string for STR_2319:    <removed string - do not use>
  warning: No string for STR_2320:    <removed string - do not use>
  warning: No string for STR_2437:    <removed string - do not use>
  warning: No string for STR_2438:    <removed string - do not use>
  warning: No string for STR_2439:    <removed string - do not use>
  warning: No string for STR_2440:    <removed string - do not use>
  warning: No string for STR_2441:    <removed string - do not use>
  warning: No string for STR_2442:    <removed string - do not use>
  warning: No string for STR_2682:    <removed string - do not use>
  warning: No string for STR_2683:    <removed string - do not use>
  warning: No string for STR_2761:    <removed string - do not use>
  warning: No string for STR_2762:    <removed string - do not use>
  warning: No string for STR_2764:    <removed string - do not use>
  warning: No string for STR_2969:    <removed string - do not use>
  warning: No string for STR_2970:    <removed string - do not use>
  warning: No string for STR_3161:    <removed string - do not use>
  warning: No string for STR_3337:    <removed string - do not use>
  warning: No string for STR_3362:    <removed string - do not use>
  warning: No string for STR_3363:    <removed string - do not use>
  warning: No string for STR_5124:    <not used anymore>
  warning: No string for STR_5494:    <not used anymore>
  warning: No string for STR_5860:    Toggle original/decompiled track drawing
info: 4137 / 4173 (99%) strings present
```

**Comment by IntelOrca** [comment]
@Nubbie What is the status of this?

**Comment by Nubbie** [comment]
@IntelOrca I'm sorry for have being so inactive with this, feel like there are some stuff in the way to finish this up with a good result that everyone can be satisfied with :U 

Anyone is more than welcome to edit this PR, screenshots etc and progress can be found at [my fork](https://github.com/Nubbie/Nubbie-Localisation/blob/master/README.md)

Progress so far: 
hrsdse

**Comment by Nubbie** [comment]
The question is:

- Possible to show the latest issue to see the newest string?
- Possible to have 2 separate parts (vanilla and OpenRCT2 strings) ?
- Possible to see the last string in the language? xox

**Comment by IntelOrca** [comment]
> Possible to show the latest issue to see the newest string?

Not sure if that's helpful, languages get updated at different speeds. A language might have to catch-up by several issues.

> Possible to have 2 separate parts (vanilla and OpenRCT2 strings) ?

I don't feel like doing the extra work for this. Particularly when eventually there won't be a distinction. I don't see the need for one now to be honest.

> Possible to see the last string in the language? xox

Maybe, but I think that can wait.

**Comment by Nubbie** [comment]
1. True, was mostly ment so people quickly could see if something new was there, will not use that

2. Will just use one bar 

3. Will put that on hold 

Presume this is getting almost done, the only thing would be to clean up the languages so the bars gets accurate? Wouldn't it be better with longer bars too? :p

**Comment by IntelOrca** [comment]
how do I get longer bars?

**Comment by Nubbie** [comment]
No idea if you can with these bars, they are from this project tho :U 
https://github.com/fehmicansaglam/progressed.io 
@Wirlie recommended them :+1:

**Comment by Nubbie** [comment]
We should scale it up a little bit so you can see a difference with 99% and 100%
Would be best if it could be stretch out too

**Comment by IntelOrca** [comment]
The API does not let you resize it, but its so simple that I could actually just implement it myself. It only edits a chunk of SVG slightly.

**Comment by IntelOrca** [comment]
Something like this maybe:?
image

**Comment by Nubbie** [comment]
@IntelOrca 
You're a progress bar genius ;p

You could scale the text to make it more clear there is a grey gap with `?scale=105` (105%) but having the bars longer would make it more clear even with the 100% scale + when I remove stuff from the 'tabs', something needs to fill them out so a longer bar wouldn't be bad
_Thanks for helping out so much :)_

Here's a picture of that bar you sent me in the list
wfa
**Which looks :+1:** 

### **Notes:**

- Maybe a slightly longer bar (A lot of empty space)
- Try using scaling 105 - 110 % (?scale=105) to add more effect and gray space after 95%
- You are more than welcome to test and edit this PR all you like if needed :smile:

**Comment by IntelOrca** [comment]
You don't need the badges on the left if the progress bars show the name of the language.

**Comment by Nubbie** [comment]
@IntelOrca Removing them will lead to an even shorter bar, the proportion would be really bad :/ 
Considering the text and all

**Comment by IntelOrca** [comment]
I don't need the point in both, just draw a bar the length you want it to be.

**Comment by Nubbie** [comment]
Think it would be better to have the language first, especially if we have the 'maintainer' tab ;o

**Comment by IntelOrca** [comment]
How long do you want the bars to be, and do you want it to say anything on the left side of it?

**Comment by Nubbie** [comment]
The left side should say the languages name and I presume it should just be a tad longer so it covers the length off the text, don't have any size to measure, I'm good with what you think :(

**Comment by IntelOrca** [comment]
what is scale?

**Comment by Nubbie** [comment]
http://progressed.io/bar/99?scale=100
hserdhserhse


awgagwawg
http://progressed.io/bar/99**?scale=150**

**Comment by Nubbie** [comment]
@IntelOrca 
Now I have to ask you about the status, any questions and such? :p 

Or have you increased the size and all ^^

**Comment by Nubbie** [comment]
How it looks ; https://github.com/Nubbie/Nubbie-Localisation/blob/83e859f6a41b8bf672e619657890f99b4c7b7e57/README.md

Todo:

- Fill in all maintainers (That want to show their name publicly in the file)
- Add length to the bars

Another PR:

- Making the bars more accurate by hashing out strings that doesn't differ from English

**Comment by Nubbie** [comment]
So what happen to this, presume the only thing left is filling out the maintainers

**Comment by Nubbie** [comment]
Any more thoughts on this?

**Comment by IntelOrca** [comment]
I haven't got round to fixing the API yet which is returning json content type instead of svg.

**Comment by Nubbie** [comment]
All maintainers for languages updated are added, the maintainers are just chosen by taking the people who often apply for issues for that language

**Comment by Nubbie** [comment]
Don't have much else I know could be improved and as far as I know, review and thoughts about it is all that's left, if not scrap
[This is how it looks](https://github.com/Nubbie/Nubbie-Localisation/blob/61e75358e657ea6807ccf8c0701290d3d5896ed3/README.md)

**Comment by IntelOrca** [comment]
Looks fine, we just need to actually remove (comment out) all the non-translated strings in those languages so they don't all appear green.

**Comment by Nubbie** [comment]
With the right instructions, I could manually check through the languages

**Pull request merged**
