### PR TITLE
zh-TW: #963, AA Scenario part 4

### PR DESCRIPTION
**Pull request by daihakken**
- Applying for issue: #963

### CODE REVIEW

**Comment by IntelOrca** [comment]
This did not pass the CI tests.

**Comment by daihakken** [comment]
I am really sorry about that, it should be mac-specific issue cause I was using TextEdit to edit the text. Using notepad from Windows seems to be fine.

**Comment by Gymnasiast** [comment]
I have fixed it.

**Comment by daihakken** [comment]
@Gymnasiast i know, thank you, but I also wanted to state the reason why my commits always fail the CI test...

**Pull request merged**
