### PR TITLE
es-ES: #2027 - STR_6398

### PR DESCRIPTION
**Pull request by frenchiveruti**
Applying for issue(s):
- #2027

### CODE REVIEW

**Comment by frenchiveruti** [comment]
How do I solve the 21 missing translations, I can't find them!

**Comment by tupaschoal** [comment]
If you click the checks tab and expand "Run checks" or [view the raw log](https://pipelines.actions.githubusercontent.com/VR0xCCUpLc2NU9ZUMqEezie0LGxaXAFRCih9Dc6F1gdt2hcOa8/_apis/pipelines/1/runs/46/signedlogcontent/3?urlExpires=2020-11-03T02%3A02%3A13.0503748Z&urlSigningMethod=HMACV1&urlSignature=TlRtFmZBO9oOnUW8kFpEYNaczugj5FRRgtXKsMvo%2Fhc%3D) you'll get the full list of all languages.

For ease, here are the missing ones in `es-ES`:
```
2020-11-02T23:49:34.5603394Z [es-ES] Missing translation: STR_6373
2020-11-02T23:49:34.5603979Z [es-ES] Missing translation: STR_6374
2020-11-02T23:49:34.5695638Z [es-ES] Missing translation: [TTPIRF02]STR_NAME
2020-11-02T23:49:34.5696315Z [es-ES] Missing translation: [TTPIRF03]STR_NAME
2020-11-02T23:49:34.5696987Z [es-ES] Missing translation: [TTPIRF04]STR_NAME
2020-11-02T23:49:34.5697654Z [es-ES] Missing translation: [TTPIRF05]STR_NAME
2020-11-02T23:49:34.5698321Z [es-ES] Missing translation: [TTPIRF07]STR_NAME
2020-11-02T23:49:34.5698987Z [es-ES] Missing translation: [TTPIRF08]STR_NAME
2020-11-02T23:49:34.5699641Z [es-ES] Missing translation: [TTRFWD01]STR_NAME
2020-11-02T23:49:34.5700309Z [es-ES] Missing translation: [TTRFWD02]STR_NAME
2020-11-02T23:49:34.5700981Z [es-ES] Missing translation: [TTRFWD03]STR_NAME
2020-11-02T23:49:34.5701649Z [es-ES] Missing translation: [TTRFWD04]STR_NAME
2020-11-02T23:49:34.5702318Z [es-ES] Missing translation: [TTRFWD05]STR_NAME
2020-11-02T23:49:34.5702993Z [es-ES] Missing translation: [TTRFWD06]STR_NAME
2020-11-02T23:49:34.5703731Z [es-ES] Missing translation: [TTRFWD07]STR_NAME
2020-11-02T23:49:34.5704417Z [es-ES] Missing translation: [TTRFWD08]STR_NAME
2020-11-02T23:49:34.5705072Z [es-ES] Missing translation: [TTRFGL01]STR_NAME
2020-11-02T23:49:34.5705743Z [es-ES] Missing translation: [TTRFGL02]STR_NAME
2020-11-02T23:49:34.5706414Z [es-ES] Missing translation: [TTRFGL03]STR_NAME
2020-11-02T23:49:34.5707076Z [es-ES] Missing translation: [ACWW33]STR_NAME
2020-11-02T23:49:34.5707728Z [es-ES] Missing translation: [ACWWF32]STR_NAME
```
Not needed:
```
2020-11-02T23:49:34.5717447Z [es-ES] Unnecessary translation: STR_3158
2020-11-02T23:49:34.5718073Z [es-ES] Unnecessary translation: STR_3159
2020-11-02T23:49:34.5718711Z [es-ES] Unnecessary translation: STR_3440
2020-11-02T23:49:34.5719343Z [es-ES] Unnecessary translation: STR_3441
2020-11-02T23:49:34.5719972Z [es-ES] Unnecessary translation: STR_3442
2020-11-02T23:49:34.5720683Z [es-ES] Unnecessary translation: STR_3443
2020-11-02T23:49:34.5721323Z [es-ES] Unnecessary translation: STR_3444
2020-11-02T23:49:34.5721957Z [es-ES] Unnecessary translation: STR_5488
2020-11-02T23:49:34.5722590Z [es-ES] Unnecessary translation: STR_5599
2020-11-02T23:49:34.5723210Z [es-ES] Unnecessary translation: STR_5728
2020-11-02T23:49:34.5723846Z [es-ES] Unnecessary translation: STR_5729
2020-11-02T23:49:34.5724480Z [es-ES] Unnecessary translation: STR_6104
2020-11-02T23:49:34.5725111Z [es-ES] Unnecessary translation: STR_6106
2020-11-02T23:49:34.5725742Z [es-ES] Unnecessary translation: STR_6108
2020-11-02T23:49:34.5726374Z [es-ES] Unnecessary translation: STR_6110
2020-11-02T23:49:34.5727001Z [es-ES] Unnecessary translation: STR_6112
2020-11-02T23:49:34.5727634Z [es-ES] Unnecessary translation: STR_6114
2020-11-02T23:49:34.5728250Z [es-ES] Unnecessary translation: STR_6117
2020-11-02T23:49:34.5728888Z [es-ES] Unnecessary translation: STR_6118
```
Same (some will be the same because words match in both languages:
```
2020-11-02T23:49:34.5520281Z [es-ES] Same translation: STR_0024
2020-11-02T23:49:34.5520827Z [es-ES] Same translation: STR_0042
2020-11-02T23:49:34.5521371Z [es-ES] Same translation: STR_0048
2020-11-02T23:49:34.5521916Z [es-ES] Same translation: STR_0069
2020-11-02T23:49:34.5522460Z [es-ES] Same translation: STR_0083
2020-11-02T23:49:34.5523002Z [es-ES] Same translation: STR_0811
2020-11-02T23:49:34.5523546Z [es-ES] Same translation: STR_0812
2020-11-02T23:49:34.5524090Z [es-ES] Same translation: STR_0814
2020-11-02T23:49:34.5524617Z [es-ES] Same translation: STR_0815
2020-11-02T23:49:34.5525164Z [es-ES] Same translation: STR_0816
2020-11-02T23:49:34.5525707Z [es-ES] Same translation: STR_0818
2020-11-02T23:49:34.5526313Z [es-ES] Same translation: STR_0819
2020-11-02T23:49:34.5526873Z [es-ES] Same translation: STR_0820
2020-11-02T23:49:34.5527416Z [es-ES] Same translation: STR_0973
2020-11-02T23:49:34.5527961Z [es-ES] Same translation: STR_1421
2020-11-02T23:49:34.5528489Z [es-ES] Same translation: STR_1736
2020-11-02T23:49:34.5529033Z [es-ES] Same translation: STR_1766
2020-11-02T23:49:34.5529573Z [es-ES] Same translation: STR_1908
2020-11-02T23:49:34.5530228Z [es-ES] Same translation: STR_1953
2020-11-02T23:49:34.5530773Z [es-ES] Same translation: STR_2001
2020-11-02T23:49:34.5531315Z [es-ES] Same translation: STR_2029
2020-11-02T23:49:34.5531858Z [es-ES] Same translation: STR_2085
2020-11-02T23:49:34.5532403Z [es-ES] Same translation: STR_2125
2020-11-02T23:49:34.5532937Z [es-ES] Same translation: STR_2147
2020-11-02T23:49:34.5533482Z [es-ES] Same translation: STR_2191
2020-11-02T23:49:34.5534034Z [es-ES] Same translation: STR_2338
2020-11-02T23:49:34.5534575Z [es-ES] Same translation: STR_2339
2020-11-02T23:49:34.5535121Z [es-ES] Same translation: STR_2340
2020-11-02T23:49:34.5535664Z [es-ES] Same translation: STR_2343
2020-11-02T23:49:34.5536206Z [es-ES] Same translation: STR_2344
2020-11-02T23:49:34.5536749Z [es-ES] Same translation: STR_2366
2020-11-02T23:49:34.5537276Z [es-ES] Same translation: STR_2367
2020-11-02T23:49:34.5537818Z [es-ES] Same translation: STR_2534
2020-11-02T23:49:34.5538374Z [es-ES] Same translation: STR_2537
2020-11-02T23:49:34.5538915Z [es-ES] Same translation: STR_2543
2020-11-02T23:49:34.5539442Z [es-ES] Same translation: STR_2545
2020-11-02T23:49:34.5539982Z [es-ES] Same translation: STR_2552
2020-11-02T23:49:34.5540526Z [es-ES] Same translation: STR_2558
2020-11-02T23:49:34.5541069Z [es-ES] Same translation: STR_2559
2020-11-02T23:49:34.5541609Z [es-ES] Same translation: STR_2566
2020-11-02T23:49:34.5542151Z [es-ES] Same translation: STR_2567
2020-11-02T23:49:34.5542785Z [es-ES] Same translation: STR_2568
2020-11-02T23:49:34.5543315Z [es-ES] Same translation: STR_2569
2020-11-02T23:49:34.5543864Z [es-ES] Same translation: STR_2570
2020-11-02T23:49:34.5544405Z [es-ES] Same translation: STR_2571
2020-11-02T23:49:34.5544945Z [es-ES] Same translation: STR_2572
2020-11-02T23:49:34.5545482Z [es-ES] Same translation: STR_2618
2020-11-02T23:49:34.5546014Z [es-ES] Same translation: STR_2621
2020-11-02T23:49:34.5546547Z [es-ES] Same translation: STR_2622
2020-11-02T23:49:34.5547077Z [es-ES] Same translation: STR_2623
2020-11-02T23:49:34.5547608Z [es-ES] Same translation: STR_2624
2020-11-02T23:49:34.5548190Z [es-ES] Same translation: STR_2625
2020-11-02T23:49:34.5548732Z [es-ES] Same translation: STR_2626
2020-11-02T23:49:34.5549272Z [es-ES] Same translation: STR_2627
2020-11-02T23:49:34.5549813Z [es-ES] Same translation: STR_2628
2020-11-02T23:49:34.5550356Z [es-ES] Same translation: STR_2629
2020-11-02T23:49:34.5550894Z [es-ES] Same translation: STR_2630
2020-11-02T23:49:34.5551438Z [es-ES] Same translation: STR_2631
2020-11-02T23:49:34.5551969Z [es-ES] Same translation: STR_2632
2020-11-02T23:49:34.5552514Z [es-ES] Same translation: STR_2634
2020-11-02T23:49:34.5553058Z [es-ES] Same translation: STR_2635
2020-11-02T23:49:34.5553598Z [es-ES] Same translation: STR_2636
2020-11-02T23:49:34.5554143Z [es-ES] Same translation: STR_2669
2020-11-02T23:49:34.5554684Z [es-ES] Same translation: STR_2670
2020-11-02T23:49:34.5555230Z [es-ES] Same translation: STR_2685
2020-11-02T23:49:34.5555759Z [es-ES] Same translation: STR_2726
2020-11-02T23:49:34.5556302Z [es-ES] Same translation: STR_2727
2020-11-02T23:49:34.5556848Z [es-ES] Same translation: STR_2740
2020-11-02T23:49:34.5557393Z [es-ES] Same translation: STR_2741
2020-11-02T23:49:34.5557940Z [es-ES] Same translation: STR_2782
2020-11-02T23:49:34.5558482Z [es-ES] Same translation: STR_2783
2020-11-02T23:49:34.5559025Z [es-ES] Same translation: STR_2865
2020-11-02T23:49:34.5559555Z [es-ES] Same translation: STR_2877
2020-11-02T23:49:34.5560089Z [es-ES] Same translation: STR_2878
2020-11-02T23:49:34.5560620Z [es-ES] Same translation: STR_2879
2020-11-02T23:49:34.5561219Z [es-ES] Same translation: STR_2880
2020-11-02T23:49:34.5561773Z [es-ES] Same translation: STR_2881
2020-11-02T23:49:34.5562314Z [es-ES] Same translation: STR_2882
2020-11-02T23:49:34.5562859Z [es-ES] Same translation: STR_2883
2020-11-02T23:49:34.5563400Z [es-ES] Same translation: STR_2884
2020-11-02T23:49:34.5563943Z [es-ES] Same translation: STR_2885
2020-11-02T23:49:34.5564477Z [es-ES] Same translation: STR_2886
2020-11-02T23:49:34.5565018Z [es-ES] Same translation: STR_2887
2020-11-02T23:49:34.5565559Z [es-ES] Same translation: STR_2888
2020-11-02T23:49:34.5566099Z [es-ES] Same translation: STR_2889
2020-11-02T23:49:34.5566639Z [es-ES] Same translation: STR_2890
2020-11-02T23:49:34.5567180Z [es-ES] Same translation: STR_2891
2020-11-02T23:49:34.5567724Z [es-ES] Same translation: STR_2892
2020-11-02T23:49:34.5568250Z [es-ES] Same translation: STR_2893
2020-11-02T23:49:34.5568805Z [es-ES] Same translation: STR_2894
2020-11-02T23:49:34.5569350Z [es-ES] Same translation: STR_2895
2020-11-02T23:49:34.5569986Z [es-ES] Same translation: STR_2896
2020-11-02T23:49:34.5570546Z [es-ES] Same translation: STR_2897
2020-11-02T23:49:34.5571088Z [es-ES] Same translation: STR_2898
2020-11-02T23:49:34.5571632Z [es-ES] Same translation: STR_2899
2020-11-02T23:49:34.5572174Z [es-ES] Same translation: STR_2901
2020-11-02T23:49:34.5572707Z [es-ES] Same translation: STR_2902
2020-11-02T23:49:34.5573250Z [es-ES] Same translation: STR_2903
2020-11-02T23:49:34.5573792Z [es-ES] Same translation: STR_2904
2020-11-02T23:49:34.5574334Z [es-ES] Same translation: STR_2905
2020-11-02T23:49:34.5574877Z [es-ES] Same translation: STR_2906
2020-11-02T23:49:34.5575423Z [es-ES] Same translation: STR_2907
2020-11-02T23:49:34.5575967Z [es-ES] Same translation: STR_3013
2020-11-02T23:49:34.5576511Z [es-ES] Same translation: STR_3247
2020-11-02T23:49:34.5578378Z [es-ES] Same translation: STR_5262
2020-11-02T23:49:34.5578926Z [es-ES] Same translation: STR_5263
2020-11-02T23:49:34.5579470Z [es-ES] Same translation: STR_5268
2020-11-02T23:49:34.5580015Z [es-ES] Same translation: STR_5305
2020-11-02T23:49:34.5580561Z [es-ES] Same translation: STR_5306
2020-11-02T23:49:34.5581090Z [es-ES] Same translation: STR_5307
2020-11-02T23:49:34.5581635Z [es-ES] Same translation: STR_5308
2020-11-02T23:49:34.5582180Z [es-ES] Same translation: STR_5309
2020-11-02T23:49:34.5582721Z [es-ES] Same translation: STR_5351
2020-11-02T23:49:34.5583265Z [es-ES] Same translation: STR_5366
2020-11-02T23:49:34.5583808Z [es-ES] Same translation: STR_5464
2020-11-02T23:49:34.5584355Z [es-ES] Same translation: STR_5476
2020-11-02T23:49:34.5584896Z [es-ES] Same translation: STR_5497
2020-11-02T23:49:34.5585426Z [es-ES] Same translation: STR_5584
2020-11-02T23:49:34.5585968Z [es-ES] Same translation: STR_5608
2020-11-02T23:49:34.5586513Z [es-ES] Same translation: STR_5609
2020-11-02T23:49:34.5587056Z [es-ES] Same translation: STR_5611
2020-11-02T23:49:34.5587607Z [es-ES] Same translation: STR_5613
2020-11-02T23:49:34.5588151Z [es-ES] Same translation: STR_5615
2020-11-02T23:49:34.5588693Z [es-ES] Same translation: STR_5619
2020-11-02T23:49:34.5589234Z [es-ES] Same translation: STR_5620
2020-11-02T23:49:34.5589762Z [es-ES] Same translation: STR_5621
2020-11-02T23:49:34.5590304Z [es-ES] Same translation: STR_5622
2020-11-02T23:49:34.5590847Z [es-ES] Same translation: STR_5623
2020-11-02T23:49:34.5591389Z [es-ES] Same translation: STR_5624
2020-11-02T23:49:34.5591933Z [es-ES] Same translation: STR_5645
2020-11-02T23:49:34.5592478Z [es-ES] Same translation: STR_5813
2020-11-02T23:49:34.5593024Z [es-ES] Same translation: STR_5814
2020-11-02T23:49:34.5593554Z [es-ES] Same translation: STR_5877
2020-11-02T23:49:34.5594097Z [es-ES] Same translation: STR_5879
2020-11-02T23:49:34.5594638Z [es-ES] Same translation: STR_5913
2020-11-02T23:49:34.5595183Z [es-ES] Same translation: STR_5964
2020-11-02T23:49:34.5595725Z [es-ES] Same translation: STR_6010
2020-11-02T23:49:34.5596331Z [es-ES] Same translation: STR_6011
2020-11-02T23:49:34.5596890Z [es-ES] Same translation: STR_6140
2020-11-02T23:49:34.5597432Z [es-ES] Same translation: STR_6280
2020-11-02T23:49:34.5597964Z [es-ES] Same translation: STR_6282
2020-11-02T23:49:34.5598506Z [es-ES] Same translation: STR_6293
2020-11-02T23:49:34.5599049Z [es-ES] Same translation: STR_6294
2020-11-02T23:49:34.5599589Z [es-ES] Same translation: STR_6295
2020-11-02T23:49:34.5600132Z [es-ES] Same translation: STR_6296
2020-11-02T23:49:34.5600675Z [es-ES] Same translation: STR_6297
2020-11-02T23:49:34.5601216Z [es-ES] Same translation: STR_6305
2020-11-02T23:49:34.5601761Z [es-ES] Same translation: STR_6308
2020-11-02T23:49:34.5602287Z [es-ES] Same translation: STR_6317
2020-11-02T23:49:34.5602830Z [es-ES] Same translation: STR_6320
2020-11-02T23:49:34.5604625Z [es-ES] Same translation: <Karts & Coasters>STR_PARK
2020-11-02T23:49:34.5605338Z [es-ES] Same translation: <Whispering Cliffs>STR_SCNR
2020-11-02T23:49:34.5606062Z [es-ES] Same translation: <Whispering Cliffs>STR_PARK
2020-11-02T23:49:34.5606775Z [es-ES] Same translation: <Three Monkeys Park>STR_SCNR
2020-11-02T23:49:34.5607464Z [es-ES] Same translation: <Three Monkeys Park>STR_PARK
2020-11-02T23:49:34.5608143Z [es-ES] Same translation: <Canary Mines>STR_SCNR
2020-11-02T23:49:34.5608803Z [es-ES] Same translation: <Canary Mines>STR_PARK
2020-11-02T23:49:34.5611319Z [es-ES] Same translation: <Barony Bridge>STR_SCNR
2020-11-02T23:49:34.5612044Z [es-ES] Same translation: <Barony Bridge>STR_PARK
2020-11-02T23:49:34.5612702Z [es-ES] Same translation: <Funtopia>STR_SCNR
2020-11-02T23:49:34.5613351Z [es-ES] Same translation: <Funtopia>STR_PARK
2020-11-02T23:49:34.5614020Z [es-ES] Same translation: <Haunted Harbour>STR_SCNR
2020-11-02T23:49:34.5614822Z [es-ES] Same translation: <Haunted Harbour>STR_PARK
2020-11-02T23:49:34.5615507Z [es-ES] Same translation: <Fun Fortress>STR_SCNR
2020-11-02T23:49:34.5616177Z [es-ES] Same translation: <Fun Fortress>STR_PARK
2020-11-02T23:49:34.5616836Z [es-ES] Same translation: <Future World>STR_SCNR
2020-11-02T23:49:34.5617495Z [es-ES] Same translation: <Future World>STR_PARK
2020-11-02T23:49:34.5618150Z [es-ES] Same translation: <Gentle Glen>STR_SCNR
2020-11-02T23:49:34.5618797Z [es-ES] Same translation: <Gentle Glen>STR_PARK
2020-11-02T23:49:34.5619456Z [es-ES] Same translation: <Jolly Jungle>STR_SCNR
2020-11-02T23:49:34.5620115Z [es-ES] Same translation: <Jolly Jungle>STR_PARK
2020-11-02T23:49:34.5620756Z [es-ES] Same translation: <Hydro Hills>STR_SCNR
2020-11-02T23:49:34.5621406Z [es-ES] Same translation: <Hydro Hills>STR_PARK
2020-11-02T23:49:34.5622077Z [es-ES] Same translation: <Sprightly Park>STR_SCNR
2020-11-02T23:49:34.5622767Z [es-ES] Same translation: <Sprightly Park>STR_PARK
2020-11-02T23:49:34.5623453Z [es-ES] Same translation: <Magic Quarters>STR_SCNR
2020-11-02T23:49:34.5624140Z [es-ES] Same translation: <Magic Quarters>STR_PARK
2020-11-02T23:49:34.5624796Z [es-ES] Same translation: <Fruit Farm>STR_SCNR
2020-11-02T23:49:34.5625439Z [es-ES] Same translation: <Fruit Farm>STR_PARK
2020-11-02T23:49:34.5626084Z [es-ES] Same translation: <Butterfly Dam>STR_SCNR
2020-11-02T23:49:34.5626763Z [es-ES] Same translation: <Butterfly Dam>STR_PARK
2020-11-02T23:49:34.5627443Z [es-ES] Same translation: <Coaster Canyon>STR_SCNR
2020-11-02T23:49:34.5628124Z [es-ES] Same translation: <Coaster Canyon>STR_PARK
2020-11-02T23:49:34.5628834Z [es-ES] Same translation: <Thunderstorm Park>STR_SCNR
2020-11-02T23:49:34.5629570Z [es-ES] Same translation: <Thunderstorm Park>STR_PARK
2020-11-02T23:49:34.5630278Z [es-ES] Same translation: <Harmonic Hills>STR_SCNR
2020-11-02T23:49:34.5630958Z [es-ES] Same translation: <Harmonic Hills>STR_PARK
2020-11-02T23:49:34.5631625Z [es-ES] Same translation: <Roman Village>STR_SCNR
2020-11-02T23:49:34.5632302Z [es-ES] Same translation: <Roman Village>STR_PARK
2020-11-02T23:49:34.5633029Z [es-ES] Same translation: <Swamp Cove>STR_SCNR
2020-11-02T23:49:34.5633687Z [es-ES] Same translation: <Swamp Cove>STR_PARK
2020-11-02T23:49:34.5634376Z [es-ES] Same translation: <Adrenaline Heights>STR_SCNR
2020-11-02T23:49:34.5635111Z [es-ES] Same translation: <Adrenaline Heights>STR_PARK
2020-11-02T23:49:34.5635802Z [es-ES] Same translation: <Utopia Park>STR_SCNR
2020-11-02T23:49:34.5636455Z [es-ES] Same translation: <Utopia Park>STR_PARK
2020-11-02T23:49:34.5637128Z [es-ES] Same translation: <Rotting Heights>STR_SCNR
2020-11-02T23:49:34.5637809Z [es-ES] Same translation: <Rotting Heights>STR_PARK
2020-11-02T23:49:34.5638490Z [es-ES] Same translation: <Fiasco Forest>STR_SCNR
2020-11-02T23:49:34.5639161Z [es-ES] Same translation: <Fiasco Forest>STR_PARK
2020-11-02T23:49:34.5639819Z [es-ES] Same translation: <Pickle Park>STR_SCNR
2020-11-02T23:49:34.5640466Z [es-ES] Same translation: <Pickle Park>STR_PARK
2020-11-02T23:49:34.5641129Z [es-ES] Same translation: <Giggle Downs>STR_SCNR
2020-11-02T23:49:34.5641794Z [es-ES] Same translation: <Giggle Downs>STR_PARK
2020-11-02T23:49:34.5642454Z [es-ES] Same translation: <Mineral Park>STR_SCNR
2020-11-02T23:49:34.5643099Z [es-ES] Same translation: <Mineral Park>STR_PARK
2020-11-02T23:49:34.5643770Z [es-ES] Same translation: <Coaster Crazy>STR_SCNR
2020-11-02T23:49:34.5644440Z [es-ES] Same translation: <Coaster Crazy>STR_PARK
2020-11-02T23:49:34.5645091Z [es-ES] Same translation: <Urban Park>STR_SCNR
2020-11-02T23:49:34.5645727Z [es-ES] Same translation: <Urban Park>STR_PARK
2020-11-02T23:49:34.5646402Z [es-ES] Same translation: <Geoffrey Gardens>STR_SCNR
2020-11-02T23:49:34.5647114Z [es-ES] Same translation: <Geoffrey Gardens>STR_PARK
2020-11-02T23:49:34.5647850Z [es-ES] Same translation: <Iceberg Islands>STR_SCNR
2020-11-02T23:49:34.5648532Z [es-ES] Same translation: <Iceberg Islands>STR_PARK
2020-11-02T23:49:34.5649194Z [es-ES] Same translation: <Volcania>STR_SCNR
2020-11-02T23:49:34.5650092Z [es-ES] Same translation: <Volcania>STR_PARK
2020-11-02T23:49:34.5650780Z [es-ES] Same translation: <Arid Heights>STR_SCNR
2020-11-02T23:49:34.5651446Z [es-ES] Same translation: <Arid Heights>STR_PARK
2020-11-02T23:49:34.5652103Z [es-ES] Same translation: <Razor Rocks>STR_SCNR
2020-11-02T23:49:34.5652754Z [es-ES] Same translation: <Razor Rocks>STR_PARK
2020-11-02T23:49:34.5653537Z [es-ES] Same translation: <Crater Lake>STR_SCNR
2020-11-02T23:49:34.5654189Z [es-ES] Same translation: <Crater Lake>STR_PARK
2020-11-02T23:49:34.5654835Z [es-ES] Same translation: <Vertigo Views>STR_SCNR
2020-11-02T23:49:34.5655509Z [es-ES] Same translation: <Vertigo Views>STR_PARK
2020-11-02T23:49:34.5656174Z [es-ES] Same translation: <Dragon's Cove>STR_SCNR
2020-11-02T23:49:34.5656834Z [es-ES] Same translation: <Dragon's Cove>STR_PARK
2020-11-02T23:49:34.5657505Z [es-ES] Same translation: <Good Knight Park>STR_SCNR
2020-11-02T23:49:34.5658192Z [es-ES] Same translation: <Good Knight Park>STR_PARK
2020-11-02T23:49:34.5658866Z [es-ES] Same translation: <Wacky Warren>STR_SCNR
2020-11-02T23:49:34.5659530Z [es-ES] Same translation: <Wacky Warren>STR_PARK
2020-11-02T23:49:34.5660181Z [es-ES] Same translation: <Grand Glacier>STR_SCNR
2020-11-02T23:49:34.5660855Z [es-ES] Same translation: <Grand Glacier>STR_PARK
2020-11-02T23:49:34.5661526Z [es-ES] Same translation: <Crazy Craters>STR_SCNR
2020-11-02T23:49:34.5662197Z [es-ES] Same translation: <Crazy Craters>STR_PARK
2020-11-02T23:49:34.5662862Z [es-ES] Same translation: <Dusty Desert>STR_SCNR
2020-11-02T23:49:34.5663522Z [es-ES] Same translation: <Dusty Desert>STR_PARK
2020-11-02T23:49:34.5664187Z [es-ES] Same translation: <Woodworm Park>STR_SCNR
2020-11-02T23:49:34.5664857Z [es-ES] Same translation: <Woodworm Park>STR_PARK
2020-11-02T23:49:34.5665505Z [es-ES] Same translation: <Icarus Park>STR_SCNR
2020-11-02T23:49:34.5666153Z [es-ES] Same translation: <Icarus Park>STR_PARK
2020-11-02T23:49:34.5666806Z [es-ES] Same translation: <Sunny Swamps>STR_SCNR
2020-11-02T23:49:34.5667471Z [es-ES] Same translation: <Sunny Swamps>STR_PARK
2020-11-02T23:49:34.5668265Z [es-ES] Same translation: <Frightmare Hills>STR_SCNR
2020-11-02T23:49:34.5669002Z [es-ES] Same translation: <Frightmare Hills>STR_PARK
2020-11-02T23:49:34.5669697Z [es-ES] Same translation: <Thunder Rocks>STR_SCNR
2020-11-02T23:49:34.5670370Z [es-ES] Same translation: <Thunder Rocks>STR_PARK
2020-11-02T23:49:34.5671024Z [es-ES] Same translation: <Octagon Park>STR_SCNR
2020-11-02T23:49:34.5671691Z [es-ES] Same translation: <Octagon Park>STR_PARK
2020-11-02T23:49:34.5672376Z [es-ES] Same translation: <Pleasure Island>STR_SCNR
2020-11-02T23:49:34.5673074Z [es-ES] Same translation: <Pleasure Island>STR_PARK
2020-11-02T23:49:34.5673756Z [es-ES] Same translation: <Icicle Worlds>STR_SCNR
2020-11-02T23:49:34.5674426Z [es-ES] Same translation: <Icicle Worlds>STR_PARK
2020-11-02T23:49:34.5675106Z [es-ES] Same translation: <Southern Sands>STR_SCNR
2020-11-02T23:49:34.5675789Z [es-ES] Same translation: <Southern Sands>STR_PARK
2020-11-02T23:49:34.5676469Z [es-ES] Same translation: <Tiny Towers>STR_SCNR
2020-11-02T23:49:34.5677104Z [es-ES] Same translation: <Tiny Towers>STR_PARK
2020-11-02T23:49:34.5677780Z [es-ES] Same translation: <Nevermore Park>STR_SCNR
2020-11-02T23:49:34.5678469Z [es-ES] Same translation: <Nevermore Park>STR_PARK
2020-11-02T23:49:34.5679132Z [es-ES] Same translation: <Pacifica>STR_SCNR
2020-11-02T23:49:34.5679781Z [es-ES] Same translation: <Pacifica>STR_PARK
2020-11-02T23:49:34.5680434Z [es-ES] Same translation: <Urban Jungle>STR_SCNR
2020-11-02T23:49:34.5681096Z [es-ES] Same translation: <Urban Jungle>STR_PARK
2020-11-02T23:49:34.5681746Z [es-ES] Same translation: <Terror Town>STR_SCNR
2020-11-02T23:49:34.5682385Z [es-ES] Same translation: <Terror Town>STR_PARK
2020-11-02T23:49:34.5683054Z [es-ES] Same translation: <Megaworld Park>STR_SCNR
2020-11-02T23:49:34.5683745Z [es-ES] Same translation: <Megaworld Park>STR_PARK
2020-11-02T23:49:34.5684410Z [es-ES] Same translation: <Venus Ponds>STR_SCNR
2020-11-02T23:49:34.5685137Z [es-ES] Same translation: <Venus Ponds>STR_PARK
2020-11-02T23:49:34.5685784Z [es-ES] Same translation: <Micro Park>STR_SCNR
2020-11-02T23:49:34.5686425Z [es-ES] Same translation: <Micro Park>STR_PARK
2020-11-02T23:49:34.5687077Z [es-ES] Same translation: <Alton Towers>STR_SCNR
2020-11-02T23:49:34.5687722Z [es-ES] Same translation: <Alton Towers>STR_PARK
2020-11-02T23:49:34.5688383Z [es-ES] Same translation: <Alton Towers>STR_DTLS
2020-11-02T23:49:34.5689047Z [es-ES] Same translation: <Heide-Park>STR_SCNR
2020-11-02T23:49:34.5689712Z [es-ES] Same translation: <Heide-Park>STR_PARK
2020-11-02T23:49:34.5690481Z [es-ES] Same translation: <Heide-Park>STR_DTLS
2020-11-02T23:49:34.5691211Z [es-ES] Same translation: <Blackpool Pleasure Beach>STR_SCNR
2020-11-02T23:49:34.5691988Z [es-ES] Same translation: <Blackpool Pleasure Beach>STR_PARK
2020-11-02T23:49:34.5692764Z [es-ES] Same translation: <Blackpool Pleasure Beach>STR_DTLS
2020-11-02T23:49:34.5693510Z [es-ES] Same translation: <Fort Anachronism>STR_SCNR
2020-11-02T23:49:34.5694219Z [es-ES] Same translation: <Fort Anachronism>STR_PARK
2020-11-02T23:49:34.5694936Z [es-ES] Same translation: <Fort Anachronism>STR_DTLS
2020-11-02T23:49:34.5708427Z [es-ES] Same translation: <Alpine Adventures>STR_SCNR
2020-11-02T23:49:34.5709156Z [es-ES] Same translation: <Alpine Adventures>STR_PARK
2020-11-02T23:49:34.5709950Z [es-ES] Same translation: <Build your own Six Flags Magic Mountain>STR_PARK
2020-11-02T23:49:34.5710757Z [es-ES] Same translation: <Build your own Six Flags Park>STR_PARK
2020-11-02T23:49:34.5711502Z [es-ES] Same translation: <Six Flags Great Adventure>STR_SCNR
2020-11-02T23:49:34.5712280Z [es-ES] Same translation: <Six Flags Great Adventure>STR_PARK
2020-11-02T23:49:34.5713032Z [es-ES] Same translation: <Six Flags Magic Mountain>STR_SCNR
2020-11-02T23:49:34.5713774Z [es-ES] Same translation: <Six Flags Magic Mountain>STR_PARK
2020-11-02T23:49:34.5714476Z [es-ES] Same translation: <Africa - Oasis>STR_SCNR
2020-11-02T23:49:34.5715196Z [es-ES] Same translation: <Australasia - Ayers Rock>STR_SCNR
2020-11-02T23:49:34.5715993Z [es-ES] Same translation: <Roaring Twenties - Prison Island>STR_PARK
2020-11-02T23:49:34.5716768Z [es-ES] Same translation: <Rock 'n' Roll - Flower Power>STR_PARK
```

**Comment by frenchiveruti** [comment]
Yes the thing is that I don't know any of these:
```
2020-11-02T23:49:34.5695638Z [es-ES] Missing translation: [TTPIRF02]STR_NAME
2020-11-02T23:49:34.5696315Z [es-ES] Missing translation: [TTPIRF03]STR_NAME
2020-11-02T23:49:34.5696987Z [es-ES] Missing translation: [TTPIRF04]STR_NAME
2020-11-02T23:49:34.5697654Z [es-ES] Missing translation: [TTPIRF05]STR_NAME
2020-11-02T23:49:34.5698321Z [es-ES] Missing translation: [TTPIRF07]STR_NAME
2020-11-02T23:49:34.5698987Z [es-ES] Missing translation: [TTPIRF08]STR_NAME
2020-11-02T23:49:34.5699641Z [es-ES] Missing translation: [TTRFWD01]STR_NAME
2020-11-02T23:49:34.5700309Z [es-ES] Missing translation: [TTRFWD02]STR_NAME
2020-11-02T23:49:34.5700981Z [es-ES] Missing translation: [TTRFWD03]STR_NAME
2020-11-02T23:49:34.5701649Z [es-ES] Missing translation: [TTRFWD04]STR_NAME
2020-11-02T23:49:34.5702318Z [es-ES] Missing translation: [TTRFWD05]STR_NAME
2020-11-02T23:49:34.5702993Z [es-ES] Missing translation: [TTRFWD06]STR_NAME
2020-11-02T23:49:34.5703731Z [es-ES] Missing translation: [TTRFWD07]STR_NAME
2020-11-02T23:49:34.5704417Z [es-ES] Missing translation: [TTRFWD08]STR_NAME
2020-11-02T23:49:34.5705072Z [es-ES] Missing translation: [TTRFGL01]STR_NAME
2020-11-02T23:49:34.5705743Z [es-ES] Missing translation: [TTRFGL02]STR_NAME
2020-11-02T23:49:34.5706414Z [es-ES] Missing translation: [TTRFGL03]STR_NAME
2020-11-02T23:49:34.5707076Z [es-ES] Missing translation: [ACWW33]STR_NAME
2020-11-02T23:49:34.5707728Z [es-ES] Missing translation: [ACWWF32]STR_NAME
```

**Comment by frenchiveruti** [comment]
Please when you can accept this PR and then I'll make another one with the missing ones, I can't handle branches tbh.  
Thanks

**Pull request merged**
