### PR TITLE
FR: Apply #806 & #816

### PR DESCRIPTION
**Pull request by rvgr**
Apply #806 & #816

### CODE REVIEW

**Comment by Nubbie** [comment]
See you shorten it to make it fix the window before the box
If it could be re-phrased (to get rid of the dot), that would be appreciated

If not, Okey for me :+1:

**Comment by rvgr** [comment]
Well it can hardly be rephrased, a more concise, literal translation of the string wouldn't mean anything in French. Anyway this abbreviation is very common and has already been used throughout the translation (including the original translation), so I don't think it will be a problem.

**Comment by Nubbie** [comment]
Then It's a OK from me :+1: 
The biggest concern was the '. :' 
Was a bit 'messy'

**Comment by rvgr** [comment]
Yes I see, nothing to worry about though, that's quite common!

**Comment by Nubbie** [comment]
OK from me :+1:

**Comment by Nubbie** [comment]
Have reviewed the new line you added, could you please insert a {NEWLINE} to break the line just like it does in the en-UK? 
Makes it easier to read in-game

Right now, it breaks at 'le fichier' which is one letter too much

image

**Comment by rvgr** [comment]
I had to add two {NEWLINE} in order to wrap the string correctly. I preferred how it wrapped without it though.

**Comment by Nubbie** [comment]
Presume that a {NEWLINE} isn't needed if you have to use two for it too wrap right, just ends up with too many lines :disappointed: 

You can revert it like it was, when reverted;
OK from me :+1:

**Comment by Nubbie** [comment]
OK from me :+1:

**Pull request merged**
