### PR TITLE
Added and updated all strings up to issue #1510

### PR DESCRIPTION
**Pull request by frenchiveruti**
If you are applying translations for an issue (or multiple), please list them below (if not, delete this text).
The only thing I didn't do is the new JSON issue at 1470

Applying for issue(s):
- #1321 
- #1327 
- #1334 
- #1338 
- #1344 
- #1349 
- #1356 
- #1359 
- #1363 
- #1367 
- #1386 
- #1390 
- #1399 
- #1400 
- #1419 
- #1424 
- #1432 
- #1442 
- #1446 
- #1450 
- #1451 
- #1454 
- #1455 
- #1461 
- #1465 
- #1473 
- #1478 
- #1481 
- #1487 
- #1496 
- #1501 
- #1509 
- #1510

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Thanks! By the way, could you start the commit messages with `es-ES:` next time, so we know which language your commits update?

**Comment by frenchiveruti** [comment]
Sure, do you mean in the title? I'm not very good with GIT.
For example:
`git commit "es-ES text of the commit"`?

**Comment by Gymnasiast** [comment]
Yes, that's exactly what I meant. :)

**Comment by frenchiveruti** [comment]
Great, will do in the future. Thanks

**Pull request merged**
