### PR TITLE
Added new strings

### PR DESCRIPTION
**Pull request by DJHasis**
I used meld,compared to en_US and added the missing strings.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
It's not necessary to add strings that are identical to en-GB.

**Comment by Gymnasiast** [comment]
**Never** compare with en_US. The source language is en_GB.

**Comment by DJHasis** [comment]
Okay, I didn't know that. I'll compare to en_GB. But should I remove the deprecated strings also?

**Comment by Gymnasiast** [comment]
Yup.

**Comment by Gymnasiast** [comment]
Since there has been no reply and this PR only adds English strings, I'll close it.

**Pull request closed without merging**
