### PR TITLE
Updated japanese.txt

### PR DESCRIPTION
**Pull request by RapleAQN**
Changed some strings can't do more at the moment

### CODE REVIEW

**Comment by RapleAQN** [comment]
would
 +STR_2369    :低
+STR_2370    :平均
+STR_2371    :高い
+STR_2372    :低
+STR_2373    :メディア
+STR_2374    :高い
+STR_2375    :非常に高い
+STR_2376    :イクストリーム
be correct then?

**Comment by AaronVanGeffen** [comment]
Sorry for the delay in reply on my part. I didn't mean to have this PR sit here for three weeks without other input.

Personally, I think the new suggestions are too close to dictionary translations -- I think we should be able to come up with something that better resembles the discrete ride rating scale they represent. I've been thinking about that this morning, though, and haven't thought of anything either. @jhako and @nickhall, any ideas?

@RapleAQN For now, would you please amend your latest translations to your commit? It can then be merged in case this issue stays open without further input.

**Comment by nickhall** [comment]
My two cents

低い
普通
高い
低い
普通
高い
非常に高い
極めて高い or 極端

**Comment by jhako** [comment]
I'm sorry I hardly do works but this is my suggestion;

STR_2369    :低い
STR_2370    :中（平均的）
STR_2371    :高い
STR_2372    :低い
STR_2373    :中（普通）
STR_2374    :高い
STR_2375    :非常に高い
STR_2376    :最高

By the way,
http://www39.atwiki.jp/rct3jpinfo/pages/25.html
This is a wiki for Japanese translation of RCT3 and it has big table of English words and Japanese.
Usually similar words are used in RCT2 & 3 and so this wiki might be useful for reference.

**Comment by nickhall** [comment]
@jhako that wiki will be a huge help, thanks!

**Comment by Nubbie** [comment]
Don't want to be that guy - But couldn't we to merge/edit this PR soon, it's been sitting here for a while :/

**Comment by nickhall** [comment]
@RapleAQN I would suggest taking the suggestions made by @jhako and updating. Then we can merge this.

If it's not resolved soon we can close and resubmit it I guess.

**Comment by Nubbie** [comment]
@RapleAQN see @nickhall 
Just want to see the blank page at the pull requests page<3
Would be just like Christmas for me

**Comment by Gymnasiast** [comment]
@Nubbie Please leave managing the process to me, that's what I'm here for.

**Comment by AaronVanGeffen** [comment]
Again, I'm sorry for letting this one sit open for feedback for weeks.

As we seem to have reached a consensus, but @RapleAQN seems unavailable at the moment, I've taken the liberty to cherry-pick their commit and @jhako's suggestions into PR #518. Please continue discussion there.

**Pull request closed without merging**
