### PR TITLE
Update es-ES.txt

### PR DESCRIPTION
**Pull request by siomy11**
If you are applying translations for an issue (or multiple), please list them below (if not, delete this text).

Applying for issue(s):
- #1072 

Might be wrong with the 'height' translation, since I feel like it could also be 'nivel' but 'altura' makes sense to me. 
@Wirlie Please fix if wrong! Thank you! :)

### CODE REVIEW

**Comment by Wirlie** [comment]
Thank you for your collaboration, all translations are correct, but I have a suggestion with the translation of the string 6051, "El ancho y la altura deben coincidir" makes sense to me, what do you think of that? Anyway, your translation is correct :P

**Comment by siomy11** [comment]
You're right ! 
La verdad no me acordaba como decir width en español Hahah 
Will change it soon, thanks!

**Comment by Wirlie** [comment]
It's ok now :ok_hand: :3 

 PD: @siomy11 ¿Usas gitter? Podemos ponernos en contacto por ahí, por si hay alguna duda :p

**Comment by siomy11** [comment]
@Wirlie No uso gitter, pero crearé una cuenta 👍 👍

**Pull request merged**
