### PR TITLE
es-ES: Apply #2936, #2938

### PR DESCRIPTION
**Pull request by dimateos**
Applying for issue(s):
- #2936 + consistency with older strings for "translucent"
- #2938

### CODE REVIEW

**Comment by Gymnasiast** [comment]
@tupaschoal Does this look alright to you?

**Comment by tupaschoal** [comment]
The patches touch es-ES, but mention pt-BR

**Comment by dimateos** [comment]
Oups sorry guys I was bit sleep deprived XD 
I copy-pasted @tupaschoal commit title as it covered the same two issues... fixing it in a sec

**Comment by Gymnasiast** [comment]
If it's any consolation, I hadn't noticed it either :')

**Pull request merged**
