### PR TITLE
zh-CN: Apply #901 #903 #913 #925 #931 #935

### PR DESCRIPTION
**Pull request by izhangfei**
If you're applying strings from a issue, please fill it out below (if not, delete this text)

- Applying for issue: #901 #903 #913 #925 #931 #935

### CODE REVIEW

**Comment by daihakken** [comment]
I've been monitoring the "machine-translation" from zh-TW to zh-CN long time ago, but there is no evidence until now (e.g. STR_5921/55). May you guys @izhangfei @tkliuxing stop it? Please translate them into your own words, it would be more meaningful to do so. Thank you.

**Comment by izhangfei** [comment]
I do my own translation, sometimes inaccurate will refer to the zh-TW translation, but not "machine-translation". zh-CN and zh-TW in most of the time translated text is the same, but one is simplified Chinese character and the other is traditional Chinese character. Also some words is different because of the two different cultural backgrounds. If we use "machine-translation", why not directly translated all Simplified Chinese from traditional Chinese text? And now Simplified Chinese translation of the text is still a large number of untranslated. I did not spend much time contributing to the translation of OpenRCT2, so the translation progress of Simplified Chinese lagged behind. If the simplified Chinese translation progress faster than traditional Chinese, can you give up the above ideas? Thank you for your interest in Simplified Chinese translation and we will make it better.

**Comment by izhangfei** [comment]
I do my own translation, sometimes inaccurate will refer to the zh-TW translation, but not "machine-translation". zh-CN and zh-TW in most of the time translated text is the same, but one is simplified Chinese character and the other is traditional Chinese character. Also some words is different because of the two different cultural backgrounds. If we use "machine-translation", why not directly translated all Simplified Chinese from traditional Chinese text? And now Simplified Chinese translation of the text is still a large number of untranslated. I did not spend much time contributing to the translation of OpenRCT2, so the translation progress of Simplified Chinese lagged behind. If the simplified Chinese translation progress faster than traditional Chinese, can you give up the above ideas? Thank you @daihakken  for your interest in Simplified Chinese translation and we will make it better.

**Comment by tkliuxing** [comment]
首先表示抱歉，我在最近一次的提交中使用了机器翻译。我会很快修正这些机器翻译造成的问题，使其符合简体中文的表达。另外，非常感谢 @daihakken 你们做的繁体中文的翻译。
PS：请原谅我没有用英文书写，因为使用中文（母语）能更符合我的本意。(machine-translation: Please forgive me for not writing in English, because the use of Chinese (native language) can be more in line with my intention.)

**Pull request closed without merging**
