### PR TITLE
zh-CN: Apply #2492 #2501 + Some minor changes

### PR DESCRIPTION
**Pull request by LPR-Michael**
Applying for issue(s):
- #2492 
- #2501 

Minor changes:
Add some ‘{NEWLINE}’ In some lines which been used in New Games window to make sure that string display well on all Fonts.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
There are merge conflicts, so I cannot merge it. You need to fix these, or enable to option to allow me to do it.

**Comment by LPR-Michael** [comment]
@Gymnasiast I'm sorry for that, How about now?

**Comment by Gymnasiast** [comment]
Unfortunately, it is still not mergeable.
I can fix it for you, but you have to check a box labelled "Allow maintainers to make changed" or something like that.

**Comment by LPR-Michael** [comment]
截屏2022-12-17 09 59 00
But this check box is already checked

**Comment by LPR-Michael** [comment]
Should I close this pull request and start a new one?

**Comment by Gymnasiast** [comment]
I fixed your branch now. For some reason, the GitHub interface didn’t let me, so I used the command line.

Closing a PR and creating a new one wouldn’t have helped you in this case, as your `master` branch was "dirty".

**Pull request merged**
