### PR TITLE
zh-CN: Apply #2814, #2815, #2821 & fix ellipsis convention

### PR DESCRIPTION
**Pull request by mrmagic2020**
Applying for issue(s):
- #2814 
- #2815 
- #2821

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
You seem to be doubling the amount of ellipses. Is this intentional?

**Comment by mrmagic2020** [comment]
> You seem to be doubling the amount of ellipses. Is this intentional?

Yes. In Chinese, the standard way of writing ellipses is having six dots, instead of three. Further reference: https://en.wikipedia.org/wiki/Ellipsis#:~:text=In%20Chinese%2C%20the%20ellipsis%20is,vertical%20space%20as%20two%20characters).

**Comment by Gymnasiast** [comment]
> > You seem to be doubling the amount of ellipses. Is this intentional?
> 
> Yes. In Chinese, the standard way of writing ellipses is having six dots, instead of three. Further reference: https://en.wikipedia.org/wiki/Ellipsis#:~:text=In%20Chinese%2C%20the%20ellipsis%20is,vertical%20space%20as%20two%20characters).

That page does say the dots are commonly vertically centred - i.e. `⋯⋯`, rather than `……` - is that correct?

**Comment by mrmagic2020** [comment]
> > > You seem to be doubling the amount of ellipses. Is this intentional?
> > 
> > 
> > Yes. In Chinese, the standard way of writing ellipses is having six dots, instead of three. Further reference: https://en.wikipedia.org/wiki/Ellipsis#:~:text=In%20Chinese%2C%20the%20ellipsis%20is,vertical%20space%20as%20two%20characters).
> 
> That page does say the dots are commonly vertically centred - i.e. `⋯⋯`, rather than `……` - is that correct?

Hmmm, interesting. Nevertheless, from my experience, people tend to write ellipses like this `……`. It's also what I get from SHIFT+6 on a Simplified Chinese keyboard... I think both will do as long as they're used consistently 😅

**Comment by Gymnasiast** [comment]
Let’s go with that, then - you know more about Chinese than we do, obviously ;)

**Pull request merged**
