### PR TITLE
sv-SE: tons of improvements to json file, lots of little tweaks to txt file

### PR DESCRIPTION
**Pull request by galfisk**
Fixed missing, wrong and mistranslations in json file. Tweaked translations in json and txt file for overall consistency, which will be especially evident in the ride and scenario picker for the scenario editor. Added some Swedishisms where appropriate which make the game feel more Swedish. Replaced typewriter quotes. Went over both files with a spell and grammar checker.
Applying for issue(s):
- #2121

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Like I said, please don't use your `develop` branch. Create one for each change.

You can use the "Resolve conflicts" function this time.

**Comment by galfisk** [comment]
> Like I said, please don't use your `develop` branch. Create one for each change.
> 
> You can use the "Resolve conflicts" function this time.

Dangit, I totally forgot. I'd rather undo this and do it right, if possible, so that I can learn. Any handy guide or tips?

**Comment by Gymnasiast** [comment]
The easiest way:

1. Go to https://github.com/OpenRCT2/Localisation
2. Navigate to the file you wish to change
3. Click the edit pencil
4. Make or copy your changes
5. Fill in the form under the file. It should automatically create a branch for you.

**Comment by galfisk** [comment]
Can do. I changed two files, does this mean I should make one branch for each file, and then submit two pull requests?

**Comment by Gymnasiast** [comment]
You could, but you can also create the branch using above method and then modify the other file in the same branch.

**Comment by galfisk** [comment]
Closing request and redoing it in what's hopefully the right way.

**Pull request closed without merging**
