### PR TITLE
translation pt-br complete

### PR DESCRIPTION
**Pull request by renansimoes**
translation to pt-br complete

### CODE REVIEW

**Comment by Gymnasiast** [comment]
I looked through all your changes. Some things:
- Please change CF back to AA. AA is the proper title, CF only the (confusing) US name.
- Please change strings 5525 and 5526 according to #291. Please also verify that you have taken all other recent changes to the language files into account. See the following:
https://github.com/OpenRCT2/Localisation/issues?utf8=%E2%9C%93&q=label%3A%22new+field%22
https://github.com/OpenRCT2/Localisation/issues?utf8=%E2%9C%93&q=label%3A%22changed+field%22

**Comment by renansimoes** [comment]
What do I have to change at 5525 and 5526? They are colours.

**Comment by Gymnasiast** [comment]
```
STR_5525 :{SMALLFONT}{BLACK}Dark water
STR_5526 :{SMALLFONT}{BLACK}Light water
```
Because they are not always turquoise or aquamarine, but take the water colour, which can be changed.

**Comment by renansimoes** [comment]
Ok, I'll change again
Em 08/12/2015 11:24, "Michael Steenbeek" <notifications@github.com>
escreveu:

**Pull request closed without merging**
