### PR TITLE
Japanese translation update

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
This resolves the discussion in #482, giving credit to the original translators.

### CODE REVIEW

**Comment by nickhall** [comment]
I may have missed some of the remaining katakana transliterations in the previous thread, but I have to question some of them, especially something like ジェントルライド. Do we want to use ライド and not 乗り物? I'd suggest 穏やかな乗り物. Similarly, instead of エアパワード maybe 空気動力? For 潜水艦ライド maybe delete the ライド and use only 潜水艦? トランスポート could be 輸送 or 交通. Some of these may be passable with their katakana equivalents, including ones I suggested, but I'd be interested in seeing what others think.

**Comment by jhako** [comment]
I think it's one of the good ways for translation to avoid using katakana as possible, but it can be unnatural for Japanese. Katanaka is, in my opinion, often used in words of things which is modern (about last 50 years?) and came from foreign, and also usually used in proper names. I feel 穏やかな乗り物 like common names of calm vehicles. So I think it's better to use not 乗り物 but ライド ,for 乗り物 is more general words. For proper names, I'd suggest 穏やかライド, 優しさライド or 安心ライド. Both of 潜水艦ライド and 潜水艦 are good, first one may be repetitive and second one may be too proper (army?), a matter of preference. トランスポート would be 移動手段 or 移動用ライド. エアパワード could be 空気力駆動 but this might be like technical terms so that I like katakana one or 空気パワー.

**Comment by nickhall** [comment]
@jhako  I'm surprised to hear that you'd prefer ライド. I didn't really see it in my searches, but it's good to know. I felt the same about overuse of kanji. Something like 空気パワー is a great balance. For transport I was going crazy trying to think of the right word for it, and 移動 was what I was trying to connect to it. Thanks as always for your contributions.

**Comment by Gymnasiast** [comment]
A release is imminent. I hope you can reach consensus by tomorrow (Western European time).

**Comment by Gymnasiast** [comment]
I have decided to merge it as it is because of the release, but please continue with the discussion.

**Pull request merged**
