### PR TITLE
Remove old music style strings

### PR DESCRIPTION
**Pull request by tupaschoal**
Applying OpenRCT2/OpenRCT2#21385 to all languages

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Ideally, we’d also update the object files.

**Comment by tupaschoal** [comment]
You mean check whether the translations there updated too?

**Comment by Gymnasiast** [comment]
Yeah, I think that some translations might not have been synced.

**Comment by tupaschoal** [comment]
> Yeah, I think that some translations might not have been synced.

I was thinking of doing it myself, but we don't know which is the most accurate, the one on objects or the one on the translation file. I'm thinking about opening an issue on the Localisation repo and have the translators notified to check if they need update, what do you think @Gymnasiast ?

**Pull request merged**
